-- =============================================================================
-- SwiftCipher update 2026-09-25: students can join their own screen channel
-- (live screens go over Realtime instead of the deprecated REST fallback).
--
-- For a database that already ran supabase/updates/2026-09-24_production_release.sql.
-- Safe to run more than once. Generated by scripts/build-update-sql.mjs.
-- Supabase dashboard -> SQL Editor -> New query -> paste all -> Run.
-- =============================================================================

-- =============================================================================
-- SwiftCipher — 0770 let a student join their own screen channel
--
-- Supabase Realtime checks the "listen" (SELECT) policy when a client joins a
-- private channel, even if the client only sends. 0760 allowed only the
-- session's teachers to listen on screen:<session>:<student>, so students
-- could not join their own channel and frames went through the REST fallback
-- (which Supabase is deprecating). The student may now join their OWN screen
-- channel while in the class; they still cannot join anyone else's.
-- =============================================================================

create or replace function app.can_listen(p_topic text) returns boolean
language plpgsql stable security definer set search_path = '' as $$
declare v_kind text := split_part(p_topic, ':', 1); v_id uuid; v_user uuid;
begin
  begin
    v_id := nullif(split_part(p_topic, ':', 2), '')::uuid;
    v_user := nullif(split_part(p_topic, ':', 3), '')::uuid;
  exception when others then return false; end;
  if v_id is null or app.tenant_id() is null then return false; end if;
  return case v_kind
    when 'session' then app.in_session(v_id) or app.can_manage_session(v_id)
    when 'staff'   then app.can_manage_session(v_id)
    -- teachers watch; the student may join only their own channel (to send frames)
    when 'screen'  then app.can_manage_session(v_id) or (v_user = auth.uid() and app.in_session(v_id))
    when 'user'    then v_id = auth.uid()
    when 'thread'  then exists (select 1 from public.chat_threads t where t.id = v_id and t.tenant_id = app.tenant_id()
                                and (t.student_id = auth.uid() or t.teacher_id = auth.uid()
                                     or (t.kind = 'group' and app.in_session(t.session_id)) or app.can_manage_class(t.class_id)))
    -- boards and games: exactly the people who can read the row (mirrors their RLS policies)
    when 'board'   then exists (select 1 from public.collab_boards b where b.id = v_id and b.tenant_id = app.tenant_id()
                                and (b.owner_id = auth.uid()
                                     or (b.session_id is not null and (app.can_manage_session(b.session_id) or app.in_session(b.session_id)))
                                     or (b.session_id is null and app.is_teacher())))
    when 'game'    then exists (select 1 from public.game_sessions g where g.id = v_id and g.tenant_id = app.tenant_id()
                                and (app.can_manage_class(g.class_id) or app.in_class(g.class_id)))
    when 'annot'   then app.in_session(v_id) or app.can_manage_session(v_id)
    else false end;
end$$;

create or replace function public.health() returns jsonb
language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('ok', true, 'db_time', now(), 'schema', '0770')
$$;

-- Done. Should return 0770:
select public.health() ->> 'schema' as schema;
