-- =============================================================================
-- SwiftCipher update 2026-09-27  (database 0790 or 0810 -> 0830)
--
-- HOW TO RUN
--   1. Supabase dashboard -> SQL Editor -> New query.
--   2. Paste this whole file and click Run (about 10 seconds).
--   3. The last result should show schema = 0830 and every check = true.
--   Safe to run more than once. It changes structure and code only: no school
--   data is deleted or rewritten.
--
-- WHAT IT ADDS
--   Fair play (0800)
--     * Answers lock once the correct answer is shown; optional second chance
--       for half credit.
--     * Untimed, accuracy-first games; class goal mode; lock a game's lobby.
--     * Private learning supports: read aloud, easy-to-read font, extra time,
--       calm mode.
--     * Students write quiz questions; teachers approve them. Gradebook export.
--   Security and reliability (0810)
--     * Class join codes can't be brute-forced (8 wrong codes / 15 min).
--     * Slide order saved in one atomic step.
--   Parents (0820)
--     * Daily and weekly reports per subject: attendance, time in class,
--       participation, accuracy, reasoning, XP, assignments, grades, six-week
--       progress, and every time the child left a lesson (what they were doing,
--       where they went, how long).
--     * Parent alerts: left a lesson, low grade, weekly summary.
--     * Private parent <-> teacher messages about a child.
--   Penetration-test fixes (0830)
--     * School admins can no longer unlock paid features beyond their plan.
--     * Anonymous error reports can't crowd out real errors.
--
-- For a database that already ran supabase/updates/2026-09-25_classroom_update.sql (0790),
-- with or without the earlier 2026-09-26 update (0810). Check first:
--   select public.health() ->> 'schema';   -- 0790 or 0810 before, 0830 after.
-- Generated by scripts/build-update-sql.mjs; do not edit by hand.
-- =============================================================================

-- =============================================================================
-- SwiftCipher — 0800 fair play: what teachers complain about in Kahoot, Blooket,
-- Gimkit, Wayground (Quizizz) and Nearpod, fixed; what they love, included.
--
-- Answers are locked once revealed. With instant feedback a student could see
--   the correct answer and resubmit it for full marks; now a revealed answer is
--   final. Optional "second chance" (Wayground's redemption questions): a wrong
--   answer may be tried once more for half credit, and the correct answer is
--   only shown after that second try.
-- Accuracy over speed (the top complaint about Kahoot): games can run untimed,
--   with no speed bonus, so careful thinkers and English learners are not
--   punished. A "class goal" mode makes the whole class work together towards
--   one target instead of ranking children against each other.
-- Lock the game (Kahoot's lobby lock): no one else can join once the teacher
--   has started, and players stay signed-in students of the class (no bots).
-- Learning supports (Wayground's accommodations), set privately per student:
--   read aloud, easy-to-read font, extra time on timed work, calm mode.
-- Students write questions (Gimkit's KitCollab): the teacher opens a quiz for
--   question writing, students submit questions with an explanation, the
--   teacher approves them into the quiz; approved authors earn XP and a badge.
-- Gradebook export (a Nearpod complaint): one CSV per class, every student and
--   every assignment.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------
alter table public.quiz_answers
  add column if not exists tries smallint not null default 1 check (tries between 1 and 2),
  add column if not exists revealed boolean not null default false;

create table if not exists public.student_supports (
  student_id      uuid primary key,
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  read_aloud      boolean not null default false,
  readable_font   boolean not null default false,
  extra_time_pct  smallint not null default 0 check (extra_time_pct in (0, 25, 50, 100)),
  calm_mode       boolean not null default false,
  note            text check (length(note) <= 500),   -- staff only, never shown to the student
  updated_by      uuid,
  updated_at      timestamptz not null default now(),
  foreign key (student_id, tenant_id) references public.users(id, tenant_id) on delete cascade
);
create index if not exists student_supports_tenant_idx on public.student_supports(tenant_id);

create table if not exists public.question_collabs (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  class_id    uuid not null,
  activity_id uuid not null,
  opened_by   uuid not null,
  is_open     boolean not null default true,
  prompt      text check (length(prompt) <= 500),    -- what the teacher wants questions about
  created_at  timestamptz not null default now(),
  unique (class_id, activity_id),
  unique (id, tenant_id),
  foreign key (class_id, tenant_id) references public.classes(id, tenant_id) on delete cascade,
  foreign key (activity_id, tenant_id) references public.activities(id, tenant_id) on delete cascade,
  foreign key (opened_by, tenant_id) references public.users(id, tenant_id) deferrable initially deferred
);
create index if not exists question_collabs_activity_idx on public.question_collabs(activity_id);
create index if not exists question_collabs_tenant_idx on public.question_collabs(tenant_id);

create table if not exists public.question_submissions (
  id           uuid primary key default gen_random_uuid(),
  tenant_id    uuid not null references public.tenants(id) on delete cascade,
  collab_id    uuid not null,
  student_id   uuid not null,
  prompt       text not null check (length(btrim(prompt)) between 5 and 1000),
  options      jsonb not null,             -- [{ "label": text, "correct": bool }], 2–6 items, exactly one correct
  explanation  text not null check (length(btrim(explanation)) between 10 and 1000),
  status       text not null default 'pending' check (status in ('pending','approved','returned')),
  feedback     text check (length(feedback) <= 1000),
  question_id  uuid,
  reviewed_by  uuid,
  reviewed_at  timestamptz,
  created_at   timestamptz not null default now(),
  unique (id, tenant_id),
  foreign key (collab_id, tenant_id) references public.question_collabs(id, tenant_id) on delete cascade,
  foreign key (student_id, tenant_id) references public.users(id, tenant_id) on delete cascade,
  foreign key (question_id) references public.questions(id) on delete set null (question_id),
  foreign key (reviewed_by) references public.users(id) on delete set null (reviewed_by)
);
create index if not exists question_submissions_collab_idx on public.question_submissions(collab_id, status);
create index if not exists question_submissions_student_idx on public.question_submissions(student_id);
create index if not exists question_submissions_tenant_idx on public.question_submissions(tenant_id);
create index if not exists question_submissions_question_idx on public.question_submissions(question_id) where question_id is not null;
create index if not exists question_submissions_reviewer_idx on public.question_submissions(reviewed_by) where reviewed_by is not null;
create index if not exists question_collabs_opened_by_idx on public.question_collabs(opened_by);

-- XP and a badge for approved questions.
alter table public.xp_events drop constraint if exists xp_events_source_check;
alter table public.xp_events add constraint xp_events_source_check
  check (source in ('answer','reasoning','completion','perfect','game','teacher','question'));
alter table public.student_badges drop constraint if exists student_badges_badge_check;
alter table public.student_badges add constraint student_badges_badge_check
  check (badge in ('first_steps','rising_star','scholar','deep_thinker','perfectionist','challenger','shout_out','game_on','author'));

-- Reads go through RPCs; students may read their own supports and submissions directly.
alter table public.student_supports enable row level security;
alter table public.question_collabs enable row level security;
alter table public.question_submissions enable row level security;
revoke all on public.student_supports, public.question_collabs, public.question_submissions from anon, authenticated;
grant select on public.student_supports, public.question_collabs, public.question_submissions to authenticated;
drop policy if exists student_supports_read on public.student_supports;
create policy student_supports_read on public.student_supports for select to authenticated
  using (tenant_id = (select app.tenant_id())
         and (student_id = (select auth.uid()) or (select app.is_admin()) or app.teaches_student(student_id)));
drop policy if exists question_collabs_read on public.question_collabs;
create policy question_collabs_read on public.question_collabs for select to authenticated
  using (tenant_id = (select app.tenant_id()) and (app.in_class(class_id) or app.can_manage_class(class_id)));
drop policy if exists question_submissions_read on public.question_submissions;
create policy question_submissions_read on public.question_submissions for select to authenticated
  using (tenant_id = (select app.tenant_id())
         and (student_id = (select auth.uid())
              or exists (select 1 from public.question_collabs c where c.id = collab_id and app.can_manage_class(c.class_id))));

-- ---------------------------------------------------------------------------
-- Badges: add "Question author"
-- ---------------------------------------------------------------------------
create or replace function app.give_badge(p_tenant uuid, p_student uuid, p_badge text) returns void
language plpgsql volatile security definer set search_path = '' as $$
declare v_new boolean;
begin
  insert into public.student_badges (student_id, tenant_id, badge) values (p_student, p_tenant, p_badge)
    on conflict do nothing returning true into v_new;
  if v_new then
    perform app.notify(p_student, 'badge', 'New badge: ' || case p_badge
        when 'first_steps' then 'First steps' when 'rising_star' then 'Rising star' when 'scholar' then 'Scholar'
        when 'deep_thinker' then 'Deep thinker' when 'perfectionist' then 'Perfectionist' when 'challenger' then 'Challenger'
        when 'shout_out' then 'Teacher shout-out' when 'game_on' then 'Game on' when 'author' then 'Question author'
        else p_badge end,
      null, '/student', 'info', jsonb_build_object('badge', p_badge));
  end if;
end$$;

-- ---------------------------------------------------------------------------
-- Answers: locked once revealed; optional second chance for half credit
-- ---------------------------------------------------------------------------
create or replace function public.submit_answer(
  p_attempt uuid, p_question uuid, p_response jsonb, p_elapsed_ms int default null
) returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_me       public.users := app.me();
  v_attempt  public.quiz_attempts;
  v_act      public.activities;
  v_q        public.questions;
  v_prev     public.quiz_answers;
  v_grade    jsonb;
  v_feedback text;
  v_instant  boolean;
  v_second   boolean;
  v_tries    smallint := 1;
  v_score    numeric;
  v_reveal   boolean;
begin
  select * into v_attempt from public.quiz_attempts where id = p_attempt and student_id = v_me.id for update;
  if v_attempt.id is null then raise exception 'Attempt not found.' using errcode = 'P0002'; end if;
  if v_attempt.status <> 'in_progress' then raise exception 'This attempt has already been submitted.' using errcode = 'P0001'; end if;
  if v_attempt.deadline_at is not null and now() > v_attempt.deadline_at + interval '5 seconds' then
    perform public.finish_attempt(p_attempt);
    raise exception 'Time is up — your attempt was submitted.' using errcode = 'P0001';
  end if;
  if length(p_response::text) > 200000 then raise exception 'Response is too large.' using errcode = '22023'; end if;

  select * into v_q from public.questions where id = p_question and activity_id = v_attempt.activity_id;
  if v_q.id is null then raise exception 'Question not in this activity.' using errcode = 'P0002'; end if;
  select * into v_act from public.activities where id = v_attempt.activity_id;
  v_feedback := coalesce(v_act.settings ->> 'show_feedback', 'after_submit');
  v_second := coalesce((v_act.settings ->> 'redemption')::boolean, false);
  v_grade := app.grade_response(v_q, p_response);
  v_instant := v_feedback = 'immediately' and v_grade ->> 'status' = 'auto_graded';
  v_score := (v_grade ->> 'score')::numeric;

  select * into v_prev from public.quiz_answers where attempt_id = p_attempt and question_id = p_question;
  if v_prev.id is not null then
    -- Once the correct answer has been shown, the answer is final.
    if v_prev.revealed then
      raise exception 'You have already answered this question. Move on to the next one.' using errcode = 'P0001';
    end if;
    -- Second chance: only after a wrong first try with instant feedback. Worth half,
    -- but never less than any partial credit the first try already earned.
    if v_instant and v_second and v_prev.is_correct is false and v_prev.tries = 1 then
      v_tries := 2;
      v_score := greatest(round(coalesce(v_score, 0) * 0.5, 2), coalesce(v_prev.auto_score, 0));
    end if;
  end if;

  -- With a second chance on, a wrong first try says "not quite" without showing the answer.
  v_reveal := v_instant and not (v_second and v_tries = 1 and (v_grade ->> 'is_correct')::boolean is false);

  insert into public.quiz_answers (tenant_id, attempt_id, question_id, response, is_correct, auto_score, status, elapsed_ms, tries, revealed)
    values (v_me.tenant_id, p_attempt, p_question, p_response, (v_grade ->> 'is_correct')::boolean,
            v_score, v_grade ->> 'status', greatest(coalesce(p_elapsed_ms, 0), 0), v_tries, v_reveal)
    on conflict (attempt_id, question_id) do update
      set response = excluded.response, is_correct = excluded.is_correct, auto_score = excluded.auto_score,
          status = excluded.status, elapsed_ms = excluded.elapsed_ms, answered_at = now(),
          tries = excluded.tries, revealed = excluded.revealed;

  if v_instant and v_reveal then
    return jsonb_build_object('saved', true, 'status', v_grade ->> 'status', 'tries', v_tries,
                              'is_correct', (v_grade ->> 'is_correct')::boolean, 'score', v_score)
           || app.reveal_answer(v_q);
  elsif v_instant then
    return jsonb_build_object('saved', true, 'status', v_grade ->> 'status', 'tries', v_tries,
                              'is_correct', false, 'second_chance', true);
  end if;
  return jsonb_build_object('saved', true, 'status', v_grade ->> 'status');
end$$;

-- ---------------------------------------------------------------------------
-- Extra time: start_attempt (0790) with the student's extra-time support applied
-- ---------------------------------------------------------------------------
create or replace function public.start_attempt(
  p_activity uuid, p_session uuid default null, p_assignment uuid default null, p_share text default null
) returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_me       public.users := app.me();
  v_act      public.activities;
  v_attempt  public.quiz_attempts;
  v_allowed  int;
  v_used     int;
  v_limit    int;
  v_extra    int;
  v_shuffle_q boolean;
  v_shuffle_o boolean;
  v_level    smallint;
  v_retry    boolean;
begin
  select * into v_act from public.activities where id = p_activity and tenant_id = v_me.tenant_id;
  if v_act.id is null then raise exception 'Activity not found.' using errcode = 'P0002'; end if;
  -- Second chances exist only with instant feedback (otherwise right/wrong stays hidden until submit).
  v_retry := coalesce(v_act.settings ->> 'show_feedback', 'after_submit') = 'immediately'
             and coalesce((v_act.settings ->> 'redemption')::boolean, false);
  if not app.attempt_context_ok(v_act, p_session, p_assignment, p_share) then
    raise exception 'This activity is not open for you right now.' using errcode = '42501';
  end if;

  -- Resume an unfinished attempt in the same context (§30 reconnect).
  select * into v_attempt from public.quiz_attempts
   where activity_id = p_activity and student_id = v_me.id and status = 'in_progress'
     and session_id is not distinct from p_session and assignment_id is not distinct from p_assignment
   order by attempt_no desc limit 1;

  if v_attempt.id is null then
    if coalesce((v_act.settings ->> 'differentiate')::boolean, false) then
      select coalesce(m.level, 2) into v_level from public.class_members m
       where m.user_id = v_me.id and m.role = 'student'
         and m.class_id = coalesce((select s.class_id from public.class_sessions s where s.id = p_session),
                                   (select a.class_id from public.assignments a where a.id = p_assignment));
      v_level := coalesce(v_level, 2);
      if not exists (select 1 from public.questions q where q.activity_id = p_activity and app.question_in_level(q.difficulty, v_level)) then
        v_level := null;
      end if;
    end if;
    v_allowed := coalesce((v_act.settings ->> 'attempts_allowed')::int, 1);
    select coalesce(max(attempt_no), 0) into v_used from public.quiz_attempts
     where activity_id = p_activity and student_id = v_me.id
       and session_id is not distinct from p_session and assignment_id is not distinct from p_assignment;
    if v_allowed > 0 and v_used >= v_allowed then
      raise exception 'No attempts left for this activity.' using errcode = 'P0001';
    end if;
    v_limit := nullif((v_act.settings ->> 'time_limit_seconds')::int, 0);
    select coalesce(extra_time_pct, 0) into v_extra from public.student_supports where student_id = v_me.id;
    if v_limit is not null and coalesce(v_extra, 0) > 0 then
      v_limit := v_limit + (v_limit * v_extra / 100);
    end if;
    insert into public.quiz_attempts (tenant_id, activity_id, student_id, session_id, assignment_id,
                                      attempt_no, seed, deadline_at, max_score, level)
      values (v_me.tenant_id, p_activity, v_me.id, p_session, p_assignment, v_used + 1,
              (random() * 2147483646)::int,
              case when v_limit is null then null else now() + make_interval(secs => v_limit) end,
              (select coalesce(sum(points), 0) from public.questions
                where activity_id = p_activity and kind <> 'poll' and app.question_in_level(difficulty, v_level)),
              v_level)
      returning * into v_attempt;
  end if;

  v_shuffle_q := coalesce((v_act.settings ->> 'shuffle_questions')::boolean, false);
  v_shuffle_o := coalesce((v_act.settings ->> 'shuffle_options')::boolean, false);

  return jsonb_build_object(
    'attempt', jsonb_build_object('id', v_attempt.id, 'attempt_no', v_attempt.attempt_no,
                                  'deadline_at', v_attempt.deadline_at, 'status', v_attempt.status,
                                  'server_now', now(), 'level', v_attempt.level),
    'activity', jsonb_build_object('id', v_act.id, 'kind', v_act.kind, 'title', v_act.title,
                                   'instructions', v_act.instructions, 'settings', v_act.settings - 'rubric_id'),
    'questions', (select coalesce(jsonb_agg(app.sanitize_question(q, v_attempt.seed, v_shuffle_o)
                                   order by case when v_shuffle_q then app.shuffle_key(v_attempt.seed, q.id::text)
                                                 else lpad(q.position::text, 6, '0') || q.created_at::text end), '[]'::jsonb)
                  from public.questions q where q.activity_id = p_activity and app.question_in_level(q.difficulty, v_attempt.level)),
    'answers', (select coalesce(jsonb_object_agg(a.question_id, a.response), '{}'::jsonb)
                from public.quiz_answers a where a.attempt_id = v_attempt.id),
    -- Which answers are final (already revealed) and which are on their second try.
    'locked', (select coalesce(jsonb_object_agg(a.question_id, jsonb_build_object('revealed', a.revealed, 'tries', a.tries, 'is_correct', a.is_correct)), '{}'::jsonb)
               from public.quiz_answers a where a.attempt_id = v_attempt.id
                and (a.revealed or (v_retry and a.tries = 1 and a.is_correct is false))));
end$$;

-- ---------------------------------------------------------------------------
-- Games: untimed (accuracy first), class goal, lobby lock
-- ---------------------------------------------------------------------------
create or replace function app.game_settings(p jsonb) returns jsonb
language sql immutable set search_path = '' as $$
  select jsonb_build_object(
    -- 0 = untimed: the teacher moves on when the class is ready; no speed bonus.
    'question_seconds', case when coalesce((p ->> 'question_seconds')::int, 20) = 0 then 0
                             else least(greatest(coalesce((p ->> 'question_seconds')::int, 20), 5), 240) end,
    'speed_bonus',      coalesce((p ->> 'speed_bonus')::boolean, true) and coalesce((p ->> 'question_seconds')::int, 20) <> 0,
    'streak_bonus',     coalesce((p ->> 'streak_bonus')::boolean, true),
    'rank_visibility',  case when coalesce((p ->> 'class_goal')::boolean, false) then 'hidden'
                             when p ->> 'rank_visibility' in ('after_each','end_only','hidden') then p ->> 'rank_visibility' else 'after_each' end,
    'display_mode',     case when p ->> 'display_mode' in ('first_name_initial','nickname','anonymous') then p ->> 'display_mode' else 'first_name_initial' end,
    'team_mode',        coalesce((p ->> 'team_mode')::boolean, false),
    'team_count',       least(greatest(coalesce((p ->> 'team_count')::int, 2), 2), 6),
    'shuffle_questions', coalesce((p ->> 'shuffle_questions')::boolean, false),
    'shuffle_options',  coalesce((p ->> 'shuffle_options')::boolean, true),
    'podium_size',      least(greatest(coalesce((p ->> 'podium_size')::int, 3), 1), 10),
    'certificates',     coalesce((p ->> 'certificates')::boolean, true),
    -- Whole class works towards one target: this share of all answers correct.
    'class_goal',       coalesce((p ->> 'class_goal')::boolean, false),
    'goal_percent',     least(greatest(coalesce((p ->> 'goal_percent')::int, 70), 30), 100),
    'locked',           coalesce((p ->> 'locked')::boolean, false))
$$;

create or replace function app.open_question(p_game public.game_sessions, p_index int) returns void
language sql volatile security definer set search_path = '' as $$
  update public.game_sessions set status = 'question', current_index = p_index,
    question_started_at = now(),
    -- Untimed questions stay open (up to an hour) until everyone answers or the teacher moves on.
    question_ends_at = now() + case when (p_game.settings ->> 'question_seconds')::int = 0 then interval '1 hour'
                                    else make_interval(secs => (p_game.settings ->> 'question_seconds')::int) end,
    started_at = coalesce(started_at, now())
  where id = p_game.id
$$;

create or replace function public.join_game(p_code text, p_nickname text default null) returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_me     public.users := app.me();
  v_game   public.game_sessions;
  v_name   text;
  v_team   uuid;
  v_player public.game_players;
  v_n      int;
begin
  select * into v_game from public.game_sessions where join_code = upper(btrim(p_code)) and status <> 'ended';
  if v_game.id is null then raise exception 'No open game with that code.' using errcode = 'P0002'; end if;
  if not app.in_class(v_game.class_id) or v_me.role <> 'student' then
    raise exception 'This game is for students in another class.' using errcode = '42501';
  end if;

  select * into v_player from public.game_players where game_id = v_game.id and user_id = v_me.id;
  if v_player.id is not null then return jsonb_build_object('game_id', v_game.id, 'player_id', v_player.id, 'display_name', v_player.display_name); end if;
  if coalesce((v_game.settings ->> 'locked')::boolean, false) then
    raise exception 'Your teacher has locked this game. Ask them to let you in.' using errcode = 'P0001';
  end if;

  case v_game.settings ->> 'display_mode'
    when 'nickname' then
      v_name := regexp_replace(btrim(coalesce(p_nickname, '')), '\s+', ' ', 'g');
      if v_name !~ '^[A-Za-z0-9][A-Za-z0-9 _-]{1,19}$' then
        raise exception 'Nicknames are 2-20 letters, numbers, spaces, - or _.' using errcode = '22023';
      end if;
      if exists (select 1 from public.game_players where game_id = v_game.id and lower(display_name) = lower(v_name)) then
        raise exception 'That nickname is taken in this game.' using errcode = 'P0001';
      end if;
    when 'anonymous' then
      select count(*) + 1 into v_n from public.game_players where game_id = v_game.id;
      v_name := 'Player ' || v_n;
    else
      v_name := app.display_name(v_me.full_name);
  end case;

  if (v_game.settings ->> 'team_mode')::boolean then
    select t.id into v_team from public.game_teams t
      left join public.game_players p on p.team_id = t.id
     where t.game_id = v_game.id group by t.id order by count(p.id), t.name limit 1;
  end if;

  insert into public.game_players (tenant_id, game_id, user_id, display_name, team_id)
    values (v_me.tenant_id, v_game.id, v_me.id, v_name, v_team) returning * into v_player;
  return jsonb_build_object('game_id', v_game.id, 'player_id', v_player.id, 'display_name', v_player.display_name);
end$$;

create or replace function public.game_control(p_game uuid, p_action text) returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare v public.game_sessions := app.require_game_host(p_game); v_total int;
begin
  v_total := coalesce(array_length(v.question_order, 1), 0);
  case p_action
    when 'start' then
      if v.status <> 'lobby' then raise exception 'The game has already started.' using errcode = 'P0001'; end if;
      perform app.open_question(v, 0);
    when 'close' then
      perform app.close_question(p_game);
    when 'next' then
      if v.status = 'question' then perform app.close_question(p_game); end if;
      if v.current_index + 1 >= v_total then perform app.finish_game(p_game);
      else perform app.open_question(v, v.current_index + 1); end if;
    when 'end' then
      perform app.finish_game(p_game);
    when 'lock' then
      update public.game_sessions set settings = settings || '{"locked": true}'::jsonb where id = p_game;
    when 'unlock' then
      update public.game_sessions set settings = settings || '{"locked": false}'::jsonb where id = p_game;
    else raise exception 'Unknown action.' using errcode = '22023';
  end case;
  perform app.audit('game.' || p_action, 'game', p_game::text);
  select * into v from public.game_sessions where id = p_game;
  return jsonb_build_object('status', v.status, 'current_index', v.current_index, 'locked', coalesce((v.settings ->> 'locked')::boolean, false));
end$$;

-- Class goal progress, for the host and every player.
create or replace function public.game_goal(p_game uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v public.game_sessions; v_players int; v_asked int; v_correct int;
begin
  select * into v from public.game_sessions where id = p_game;
  if v.id is null then raise exception 'Game not found.' using errcode = 'P0002'; end if;
  if not app.can_manage_class(v.class_id) and not app.in_class(v.class_id) then raise exception 'Not your game.' using errcode = '42501'; end if;
  select count(*) into v_players from public.game_players where game_id = p_game;
  v_asked := greatest(v.current_index + 1, 0);
  select count(*) into v_correct from public.game_answers where game_id = p_game and is_correct;
  return jsonb_build_object('enabled', coalesce((v.settings ->> 'class_goal')::boolean, false),
    'correct', v_correct,
    'target', ceil(v_players * coalesce(array_length(v.question_order, 1), 0) * (v.settings ->> 'goal_percent')::numeric / 100),
    'possible_so_far', v_players * v_asked,
    'goal_percent', (v.settings ->> 'goal_percent')::int);
end$$;

-- ---------------------------------------------------------------------------
-- Learning supports (accommodations), set privately by the student's teachers
-- ---------------------------------------------------------------------------
create or replace function public.set_student_supports(
  p_class uuid, p_student uuid, p_read_aloud boolean, p_readable_font boolean, p_extra_time_pct int,
  p_calm_mode boolean, p_note text default null
) returns void
language plpgsql volatile security definer set search_path = '' as $$
declare v_me public.users := app.me();
begin
  if not app.can_manage_class(p_class) then raise exception 'Not your class.' using errcode = '42501'; end if;
  if not exists (select 1 from public.class_members where class_id = p_class and user_id = p_student and role = 'student') then
    raise exception 'That student is not in this class.' using errcode = 'P0002';
  end if;
  if coalesce(p_extra_time_pct, 0) not in (0, 25, 50, 100) then
    raise exception 'Extra time is 0, 25, 50 or 100 percent.' using errcode = '22023';
  end if;
  insert into public.student_supports (student_id, tenant_id, read_aloud, readable_font, extra_time_pct, calm_mode, note, updated_by, updated_at)
    values (p_student, v_me.tenant_id, coalesce(p_read_aloud, false), coalesce(p_readable_font, false),
            coalesce(p_extra_time_pct, 0), coalesce(p_calm_mode, false), nullif(btrim(coalesce(p_note, '')), ''), v_me.id, now())
    on conflict (student_id) do update set read_aloud = excluded.read_aloud, readable_font = excluded.readable_font,
      extra_time_pct = excluded.extra_time_pct, calm_mode = excluded.calm_mode, note = excluded.note,
      updated_by = excluded.updated_by, updated_at = now();
  perform app.audit('student.supports_set', 'user', p_student::text,
    jsonb_build_object('class_id', p_class, 'read_aloud', p_read_aloud, 'readable_font', p_readable_font,
                       'extra_time_pct', p_extra_time_pct, 'calm_mode', p_calm_mode));
end$$;

create or replace function public.class_supports(p_class uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not app.can_manage_class(p_class) then raise exception 'Not your class.' using errcode = '42501'; end if;
  return (select coalesce(jsonb_agg(jsonb_build_object(
      'student_id', u.id, 'name', u.full_name,
      'read_aloud', coalesce(s.read_aloud, false), 'readable_font', coalesce(s.readable_font, false),
      'extra_time_pct', coalesce(s.extra_time_pct, 0), 'calm_mode', coalesce(s.calm_mode, false), 'note', s.note)
      order by u.full_name), '[]'::jsonb)
    from public.class_members m join public.users u on u.id = m.user_id
    left join public.student_supports s on s.student_id = u.id
    where m.class_id = p_class and m.role = 'student');
end$$;

-- The student's own supports (the staff note is never included).
create or replace function public.my_supports() returns jsonb
language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('read_aloud', coalesce(s.read_aloud, false), 'readable_font', coalesce(s.readable_font, false),
                            'extra_time_pct', coalesce(s.extra_time_pct, 0), 'calm_mode', coalesce(s.calm_mode, false))
  from (select 1) x left join public.student_supports s on s.student_id = auth.uid()
$$;

-- ---------------------------------------------------------------------------
-- Students write questions (teacher approves)
-- ---------------------------------------------------------------------------
create or replace function public.open_question_collab(p_class uuid, p_activity uuid, p_open boolean, p_prompt text default null)
returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare v_me public.users := app.me(); v public.question_collabs; v_title text;
begin
  if not app.can_manage_class(p_class) then raise exception 'Not your class.' using errcode = '42501'; end if;
  select title into v_title from public.activities where id = p_activity and tenant_id = v_me.tenant_id;
  if v_title is null or not app.can_view_activity(p_activity) then raise exception 'Quiz not found.' using errcode = 'P0002'; end if;
  insert into public.question_collabs (tenant_id, class_id, activity_id, opened_by, is_open, prompt)
    values (v_me.tenant_id, p_class, p_activity, v_me.id, p_open, nullif(btrim(coalesce(p_prompt, '')), ''))
    on conflict (class_id, activity_id) do update set is_open = excluded.is_open,
      prompt = coalesce(excluded.prompt, public.question_collabs.prompt)
    returning * into v;
  if p_open then
    perform app.notify(m.user_id, 'question_collab', 'Write a question for ' || v_title,
                       coalesce(v.prompt, 'Your teacher wants your best question. Include the right answer and why.'),
                       '/student', 'info', jsonb_build_object('collab_id', v.id))
    from public.class_members m where m.class_id = p_class and m.role = 'student';
  end if;
  perform app.audit(case when p_open then 'collab.opened' else 'collab.closed' end, 'question_collab', v.id::text);
  return to_jsonb(v);
end$$;

create or replace function public.my_collabs() returns jsonb
language sql stable security definer set search_path = '' as $$
  select coalesce(jsonb_agg(jsonb_build_object(
      'id', c.id, 'title', a.title, 'class', cl.name, 'prompt', c.prompt,
      'mine', (select coalesce(jsonb_agg(jsonb_build_object('id', s.id, 'prompt', s.prompt, 'status', s.status, 'feedback', s.feedback)
                                         order by s.created_at desc), '[]'::jsonb)
               from public.question_submissions s where s.collab_id = c.id and s.student_id = auth.uid()))
      order by c.created_at desc), '[]'::jsonb)
  from public.question_collabs c
  join public.class_members m on m.class_id = c.class_id and m.user_id = auth.uid() and m.role = 'student'
  join public.activities a on a.id = c.activity_id
  join public.classes cl on cl.id = c.class_id
  where c.is_open
$$;

create or replace function public.submit_question(p_collab uuid, p_prompt text, p_options jsonb, p_explanation text)
returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare v_me public.users := app.me(); v_c public.question_collabs; v_n int; v_correct int; v_id uuid;
begin
  select * into v_c from public.question_collabs where id = p_collab;
  if v_c.id is null or not v_c.is_open then raise exception 'Question writing is closed for this quiz.' using errcode = 'P0001'; end if;
  if not exists (select 1 from public.class_members where class_id = v_c.class_id and user_id = v_me.id and role = 'student') then
    raise exception 'This is for another class.' using errcode = '42501';
  end if;
  if jsonb_typeof(p_options) <> 'array' then raise exception 'Add answer choices.' using errcode = '22023'; end if;
  v_n := jsonb_array_length(p_options);
  select count(*) into v_correct from jsonb_array_elements(p_options) o where (o ->> 'correct')::boolean;
  if v_n < 2 or v_n > 6 then raise exception 'Give between 2 and 6 answer choices.' using errcode = '22023'; end if;
  if v_correct <> 1 then raise exception 'Mark exactly one choice as correct.' using errcode = '22023'; end if;
  if exists (select 1 from jsonb_array_elements(p_options) o where length(btrim(coalesce(o ->> 'label', ''))) not between 1 and 300) then
    raise exception 'Every choice needs text (up to 300 characters).' using errcode = '22023';
  end if;
  if length(btrim(coalesce(p_explanation, ''))) < 10 then
    raise exception 'Explain why the correct answer is right (at least one sentence).' using errcode = '22023';
  end if;
  if (select count(*) from public.question_submissions where collab_id = p_collab and student_id = v_me.id and status = 'pending') >= 5 then
    raise exception 'You have 5 questions waiting for your teacher. Wait for feedback before adding more.' using errcode = 'P0001';
  end if;
  insert into public.question_submissions (tenant_id, collab_id, student_id, prompt, options, explanation)
    values (v_me.tenant_id, p_collab, v_me.id, btrim(p_prompt),
            (select jsonb_agg(jsonb_build_object('label', btrim(o ->> 'label'), 'correct', coalesce((o ->> 'correct')::boolean, false)))
             from jsonb_array_elements(p_options) o),
            btrim(p_explanation))
    returning id into v_id;
  return jsonb_build_object('id', v_id);
end$$;

create or replace function public.collab_submissions(p_activity uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  return (select coalesce(jsonb_agg(jsonb_build_object(
      'id', s.id, 'student', u.full_name, 'class', cl.name, 'prompt', s.prompt, 'options', s.options,
      'explanation', s.explanation, 'status', s.status, 'feedback', s.feedback, 'created_at', s.created_at)
      order by (s.status = 'pending') desc, s.created_at), '[]'::jsonb)
    from public.question_submissions s
    join public.question_collabs c on c.id = s.collab_id
    join public.users u on u.id = s.student_id
    join public.classes cl on cl.id = c.class_id
    where c.activity_id = p_activity and app.can_manage_class(c.class_id));
end$$;

create or replace function public.review_question_submission(p_submission uuid, p_action text, p_feedback text default null)
returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare v_me public.users := app.me(); v_s public.question_submissions; v_c public.question_collabs; v_q uuid; v_pos int; v_name text;
begin
  select * into v_s from public.question_submissions where id = p_submission for update;
  if v_s.id is null then raise exception 'Question not found.' using errcode = 'P0002'; end if;
  select * into v_c from public.question_collabs where id = v_s.collab_id;
  if not app.can_manage_class(v_c.class_id) then raise exception 'Not your class.' using errcode = '42501'; end if;
  if v_s.status = 'approved' then raise exception 'Already added to the quiz.' using errcode = 'P0001'; end if;

  if p_action = 'approve' then
    select coalesce(max(position), -1) + 1 into v_pos from public.questions where activity_id = v_c.activity_id;
    select full_name into v_name from public.users where id = v_s.student_id;
    insert into public.questions (tenant_id, activity_id, owner_id, kind, prompt, explanation, points, position, config)
      values (v_s.tenant_id, v_c.activity_id, v_me.id, 'mcq', v_s.prompt, v_s.explanation, 1, v_pos,
              jsonb_build_object('authored_by', app.display_name(v_name)))
      returning id into v_q;
    insert into public.question_options (tenant_id, question_id, label, is_correct, position)
      select v_s.tenant_id, v_q, o.value ->> 'label', (o.value ->> 'correct')::boolean, (o.ordinality - 1)::int
      from jsonb_array_elements(v_s.options) with ordinality o;
    update public.question_submissions set status = 'approved', question_id = v_q, feedback = nullif(btrim(coalesce(p_feedback, '')), ''),
      reviewed_by = v_me.id, reviewed_at = now() where id = p_submission;
    perform app.give_xp(v_s.tenant_id, v_s.student_id, v_c.class_id, 'question', v_s.id, 25, 'Your question was added to the quiz');
    perform app.give_badge(v_s.tenant_id, v_s.student_id, 'author');
  elsif p_action = 'return' then
    if length(btrim(coalesce(p_feedback, ''))) < 3 then
      raise exception 'Tell the student what to improve.' using errcode = '22023';
    end if;
    update public.question_submissions set status = 'returned', feedback = btrim(p_feedback),
      reviewed_by = v_me.id, reviewed_at = now() where id = p_submission;
    perform app.notify(v_s.student_id, 'question_returned', 'Your teacher sent your question back', btrim(p_feedback), '/student', 'info',
                       jsonb_build_object('submission_id', v_s.id));
  else
    raise exception 'Unknown action.' using errcode = '22023';
  end if;
  perform app.audit('collab.' || p_action, 'question_submission', p_submission::text);
  return jsonb_build_object('status', case when p_action = 'approve' then 'approved' else 'returned' end, 'question_id', v_q);
end$$;

-- ---------------------------------------------------------------------------
-- Gradebook: every student and every assignment in a class (CSV export)
-- ---------------------------------------------------------------------------
create or replace function public.class_gradebook(p_class uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not app.can_manage_class(p_class) then raise exception 'Not your class.' using errcode = '42501'; end if;
  return jsonb_build_object(
    'assignments', (select coalesce(jsonb_agg(jsonb_build_object('id', a.id, 'title', a.title, 'due_at', a.due_at,
                      'points', a.points_possible) order by a.due_at nulls last, a.created_at), '[]'::jsonb)
                    from public.assignments a where a.class_id = p_class and a.status <> 'draft'),
    'students', (select coalesce(jsonb_agg(jsonb_build_object('id', u.id, 'name', u.full_name, 'email', u.email,
                   'scores', (select coalesce(jsonb_object_agg(a.id, jsonb_build_object(
                        'score', case when g.score is not null then g.score
                                      when t.max_score > 0 and t.score is not null then round(t.score / t.max_score * a.points_possible, 2) end,
                        'late', s.is_late, 'status', s.status)), '{}'::jsonb)
                      from public.assignments a
                      join lateral (select * from public.submissions s where s.assignment_id = a.id and s.student_id = u.id
                                    order by s.attempt_no desc limit 1) s on true
                      left join public.grades g on g.submission_id = s.id
                      left join public.quiz_attempts t on t.id = s.attempt_id
                      where a.class_id = p_class and a.status <> 'draft'))
                   order by u.full_name), '[]'::jsonb)
                 from public.class_members m join public.users u on u.id = m.user_id
                 where m.class_id = p_class and m.role = 'student'));
end$$;

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------
revoke execute on function public.game_goal(uuid), public.set_student_supports(uuid, uuid, boolean, boolean, int, boolean, text),
  public.class_supports(uuid), public.my_supports(), public.open_question_collab(uuid, uuid, boolean, text), public.my_collabs(),
  public.submit_question(uuid, text, jsonb, text), public.collab_submissions(uuid),
  public.review_question_submission(uuid, text, text), public.class_gradebook(uuid)
  from public, anon;
grant execute on function public.game_goal(uuid), public.set_student_supports(uuid, uuid, boolean, boolean, int, boolean, text),
  public.class_supports(uuid), public.my_supports(), public.open_question_collab(uuid, uuid, boolean, text), public.my_collabs(),
  public.submit_question(uuid, text, jsonb, text), public.collab_submissions(uuid),
  public.review_question_submission(uuid, text, text), public.class_gradebook(uuid)
  to authenticated, service_role;

create or replace function public.health() returns jsonb
language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('ok', true, 'db_time', now(), 'schema', '0800')
$$;

-- =============================================================================
-- SwiftCipher — 0810 fixes from the full-project audit
--
-- Join codes can't be brute-forced: wrong class codes are limited per account.
-- Slide order is written in one atomic statement. The editor used to renumber
-- slides with one UPDATE per slide from the browser; a dropped connection part
-- way through left duplicate or missing positions (slides shown out of order).
-- =============================================================================

-- p_order: every slide id of the lesson, in the new order. Positions become 0..n-1.
create or replace function public.reorder_slides(p_lesson uuid, p_order uuid[]) returns void
language plpgsql volatile security definer set search_path = '' as $$
declare v_count int;
begin
  if not app.can_edit_lesson(p_lesson) then raise exception 'You can''t edit this lesson.' using errcode = '42501'; end if;
  select count(*) into v_count from public.lesson_slides where lesson_id = p_lesson;
  if coalesce(array_length(p_order, 1), 0) <> v_count
     or (select count(distinct x) from unnest(p_order) x) <> v_count
     or exists (select 1 from unnest(p_order) x where not exists (
          select 1 from public.lesson_slides s where s.id = x and s.lesson_id = p_lesson)) then
    raise exception 'The slide list changed. Reload the lesson and try again.' using errcode = 'P0001';
  end if;
  update public.lesson_slides s set position = o.ord - 1
    from unnest(p_order) with ordinality o(id, ord)
   where s.id = o.id and s.lesson_id = p_lesson and s.position is distinct from o.ord - 1;
end$$;

revoke execute on function public.reorder_slides(uuid, uuid[]) from public, anon;
grant execute on function public.reorder_slides(uuid, uuid[]) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Join-code guessing protection. Class codes are 6 characters (easy for
-- children to type); with ~1M active classes a script could otherwise find a
-- real class in about 900 guesses and enrol itself as a student. Wrong codes
-- are now limited to 8 per account per 15 minutes, and the teacher is still
-- told whenever a student joins.
-- ---------------------------------------------------------------------------
create table if not exists public.code_attempts (
  id      bigint generated always as identity primary key,
  user_id uuid not null,
  at      timestamptz not null default now()
);
create index if not exists code_attempts_user_idx on public.code_attempts(user_id, at desc);
alter table public.code_attempts enable row level security;
revoke all on public.code_attempts from anon, authenticated;

create or replace function public.redeem_code(p_code text, p_full_name text default null)
returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_uid     uuid := auth.uid();
  v_code    text := upper(btrim(coalesce(p_code, '')));
  v_email   text;
  v_meta    jsonb;
  v_user    public.users;
  v_class   public.classes;
  v_invite  public.invites;
  v_name    text;
  v_count   bigint;
begin
  if v_uid is null then raise exception 'Sign in first.' using errcode = '42501'; end if;
  -- Guessing protection: class codes are short enough to type, so wrong guesses are limited.
  if (select count(*) from public.code_attempts where user_id = v_uid and at > now() - interval '15 minutes') >= 8 then
    raise exception 'Too many wrong codes. Wait 15 minutes, then check the code with your teacher.' using errcode = 'P0001';
  end if;
  if v_code !~ '^[A-Z0-9]{6,12}$' then raise exception 'That code is not valid.' using errcode = '22023'; end if;

  select email, raw_user_meta_data into v_email, v_meta from auth.users where id = v_uid;
  select * into v_user from public.users where id = v_uid;
  v_name := coalesce(nullif(btrim(p_full_name), ''), nullif(btrim(v_meta ->> 'full_name'), ''),
                     split_part(coalesce(v_email, 'user'), '@', 1));

  -- Invite codes take precedence (8-12 chars); class codes are 6-8.
  select * into v_invite from public.invites
   where code = v_code and revoked_at is null and expires_at > now() and uses < max_uses
   for update;

  if v_invite.id is not null then
    if v_invite.email is not null and lower(v_invite.email) <> lower(coalesce(v_email, '')) then
      raise exception 'This invite was issued for a different email address.' using errcode = '42501';
    end if;

    if v_user.id is null then
      insert into public.users (id, tenant_id, email, full_name, role)
        values (v_uid, v_invite.tenant_id, coalesce(v_email, ''), v_name, v_invite.role)
        returning * into v_user;
      if v_invite.role = 'student' then
        insert into public.student_profiles (user_id, tenant_id) values (v_uid, v_invite.tenant_id);
      elsif v_invite.role in ('teacher','school_admin','it_admin') then
        insert into public.teacher_profiles (user_id, tenant_id) values (v_uid, v_invite.tenant_id);
      end if;
    elsif v_user.tenant_id <> v_invite.tenant_id then
      raise exception 'This code belongs to a different school.' using errcode = '42501';
    elsif v_user.role <> v_invite.role then
      raise exception 'This invite is for a % account.', v_invite.role using errcode = 'P0001';
    end if;

    if v_invite.class_id is not null then
      insert into public.class_members (class_id, user_id, tenant_id, role)
        values (v_invite.class_id, v_uid, v_invite.tenant_id,
                case when v_invite.role = 'student' then 'student' else 'teacher' end)
        on conflict (class_id, user_id) do nothing;
    end if;
    if v_invite.role = 'parent' then
      insert into public.parent_links (tenant_id, parent_id, student_id)
        values (v_invite.tenant_id, v_uid, v_invite.student_id)
        on conflict (parent_id, student_id) do update set revoked_at = null;
    end if;

    update public.invites set uses = uses + 1 where id = v_invite.id;
    perform app.audit('invite.redeemed', 'invite', v_invite.id::text,
                      jsonb_build_object('role', v_invite.role), v_invite.tenant_id, v_uid);
    return jsonb_build_object('tenant_id', v_invite.tenant_id, 'role', v_user.role,
                              'class_id', v_invite.class_id, 'kind', 'invite');
  end if;

  select * into v_class from public.classes where join_code = v_code and archived_at is null;
  if v_class.id is null then
    -- Returned, not raised: raising would roll back the attempt we need to count.
    delete from public.code_attempts where user_id = v_uid and at < now() - interval '1 day';
    insert into public.code_attempts (user_id) values (v_uid);
    return jsonb_build_object('error', 'No class or invite matches that code.', 'code', 'P0002');
  end if;

  if v_user.id is null then
    insert into public.users (id, tenant_id, email, full_name, role)
      values (v_uid, v_class.tenant_id, coalesce(v_email, ''), v_name, 'student')
      returning * into v_user;
    insert into public.student_profiles (user_id, tenant_id) values (v_uid, v_class.tenant_id);
  elsif v_user.tenant_id <> v_class.tenant_id then
    raise exception 'This class belongs to a different school.' using errcode = '42501';
  elsif v_user.role <> 'student' then
    raise exception 'Class codes are for students. Ask an administrator to add you as a teacher.' using errcode = 'P0001';
  end if;

  if not exists (select 1 from public.class_members where class_id = v_class.id and user_id = v_uid) then
    select count(*) into v_count from public.class_members where class_id = v_class.id and role = 'student';
    if not app.within_limit(v_class.tenant_id, 'students_per_class', v_count) then
      raise exception 'This class is full on the current plan.' using errcode = 'P0001';
    end if;
    insert into public.class_members (class_id, user_id, tenant_id, role)
      values (v_class.id, v_uid, v_class.tenant_id, 'student');
    perform app.notify(v_class.teacher_id, 'student_joined', v_name || ' joined ' || v_class.name,
                       null, '/teacher/classes/' || v_class.id, 'info',
                       jsonb_build_object('class_id', v_class.id, 'student_id', v_uid));
  end if;

  return jsonb_build_object('tenant_id', v_class.tenant_id, 'role', 'student',
                            'class_id', v_class.id, 'class_name', v_class.name, 'kind', 'class');
end$$;

create or replace function public.health() returns jsonb
language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('ok', true, 'db_time', now(), 'schema', '0810')
$$;

-- =============================================================================
-- SwiftCipher — 0820 parent reports, parent alerts, parent–teacher messaging
--
-- What parents get (the school turns the parent portal on):
--   • A daily and a weekly report for each child, per subject: lessons
--     attended and time in class, participation ("interactiveness"), answers
--     and accuracy, explained reasoning, hands raised, XP and badges,
--     assignments (done / late / missing), released grades, and the trend over
--     the last six weeks.
--   • Focus: every time the child left the lesson — when, which lesson and
--     slide or activity they were on, where they went (the site and page title
--     on school-managed browsers; the reason on other devices), how long they
--     were away and whether they came back. Schools can limit parents to
--     counts only. Screenshots are never shown to parents: they can contain
--     other children's messages and names.
--   • Alerts they choose per child (Canvas Parent-style): the moment the child
--     leaves a lesson, a grade below their own threshold, and a weekly summary
--     every Friday afternoon (school time zone). Every guardian linked to the
--     child gets their own settings (unlike tools with one parent per child).
--   • Private messages with each subject teacher about their child (the child
--     cannot see them), next to the report.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Settings
-- ---------------------------------------------------------------------------
alter table public.tenant_settings
  add column if not exists parent_focus_details boolean not null default true;
grant update (parent_focus_details) on public.tenant_settings to authenticated;

-- ---------------------------------------------------------------------------
-- Leave events remember what the student was doing and where they went
-- ---------------------------------------------------------------------------
alter table public.environment_events
  add column if not exists page_title      text,
  add column if not exists lesson_context  jsonb,
  add column if not exists away_started_at timestamptz;
create index if not exists environment_events_student_time_idx on public.environment_events(student_id, created_at desc);

create or replace function app.event_context() returns trigger
language plpgsql security definer set search_path = '' as $$
declare v_s public.class_sessions; v_slide int; v_away timestamptz; v_lesson text; v_heading text; v_activity text; v_class text;
begin
  select * into v_s from public.class_sessions where id = new.class_session_id;
  if v_s.id is null then return new; end if;
  select p.current_slide, p.away_since into v_slide, v_away
    from public.session_participants p where p.session_id = new.class_session_id and p.user_id = new.student_id;
  v_slide := case when v_s.mode = 'student_paced' then coalesce(v_slide, v_s.current_slide) else v_s.current_slide end;
  select title into v_lesson from public.lessons where id = v_s.lesson_id;
  select nullif(btrim(content ->> 'heading'), '') into v_heading
    from public.lesson_slides where lesson_id = v_s.lesson_id and position = v_slide limit 1;
  select title into v_activity from public.activities where id = v_s.active_activity_id;
  select name into v_class from public.classes where id = v_s.class_id;
  new.lesson_context := jsonb_strip_nulls(jsonb_build_object(
    'class', v_class, 'lesson', v_lesson,
    'slide', case when v_s.lesson_id is not null then v_slide + 1 end, 'slide_heading', v_heading, 'activity', v_activity));
  -- Managed browsers (extension) know the page the student switched to.
  if new.page_title is null then
    select left(b.active_title, 300) into new.page_title from public.browser_sessions b
     where b.class_session_id = new.class_session_id and b.student_id = new.student_id
     order by b.last_heartbeat_at desc limit 1;
  end if;
  new.away_started_at := coalesce(new.away_started_at, v_away, now());
  return new;
end$$;
drop trigger if exists environment_events_context on public.environment_events;
create trigger environment_events_context before insert on public.environment_events
  for each row execute function app.event_context();

-- ---------------------------------------------------------------------------
-- Parent alert preferences (one row per guardian per child)
-- ---------------------------------------------------------------------------
create table if not exists public.parent_alert_prefs (
  parent_id       uuid not null,
  student_id      uuid not null,
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  alert_on_leave  boolean not null default false,
  weekly_digest   boolean not null default true,
  low_score_below smallint check (low_score_below is null or low_score_below between 1 and 100),
  last_digest_at  timestamptz,
  updated_at      timestamptz not null default now(),
  primary key (parent_id, student_id),
  foreign key (parent_id, tenant_id) references public.users(id, tenant_id) on delete cascade,
  foreign key (student_id, tenant_id) references public.users(id, tenant_id) on delete cascade
);
create index if not exists parent_alert_prefs_student_idx on public.parent_alert_prefs(student_id);
create index if not exists parent_alert_prefs_tenant_idx on public.parent_alert_prefs(tenant_id);
alter table public.parent_alert_prefs enable row level security;
revoke all on public.parent_alert_prefs from anon, authenticated;
grant select on public.parent_alert_prefs to authenticated;
drop policy if exists parent_alert_prefs_read on public.parent_alert_prefs;
create policy parent_alert_prefs_read on public.parent_alert_prefs for select to authenticated
  using (parent_id = (select auth.uid()));

create or replace function public.parent_alerts(p_student uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v public.parent_alert_prefs;
begin
  if not app.is_parent_of(p_student) then raise exception 'Not your child.' using errcode = '42501'; end if;
  select * into v from public.parent_alert_prefs where parent_id = auth.uid() and student_id = p_student;
  return jsonb_build_object('alert_on_leave', coalesce(v.alert_on_leave, false), 'weekly_digest', coalesce(v.weekly_digest, true),
                            'low_score_below', v.low_score_below);
end$$;

create or replace function public.set_parent_alerts(p_student uuid, p_alert_on_leave boolean, p_weekly_digest boolean, p_low_score_below int default null)
returns void
language plpgsql volatile security definer set search_path = '' as $$
declare v_me public.users := app.me();
begin
  if not app.is_parent_of(p_student) then raise exception 'Not your child.' using errcode = '42501'; end if;
  if p_low_score_below is not null and p_low_score_below not between 1 and 100 then
    raise exception 'Choose a percentage between 1 and 100.' using errcode = '22023';
  end if;
  insert into public.parent_alert_prefs (parent_id, student_id, tenant_id, alert_on_leave, weekly_digest, low_score_below, updated_at)
    values (v_me.id, p_student, v_me.tenant_id, coalesce(p_alert_on_leave, false), coalesce(p_weekly_digest, true), p_low_score_below, now())
    on conflict (parent_id, student_id) do update set alert_on_leave = excluded.alert_on_leave, weekly_digest = excluded.weekly_digest,
      low_score_below = excluded.low_score_below, updated_at = now();
end$$;

-- Tell opted-in guardians the moment their child leaves a lesson (never for a lost connection).
create or replace function app.event_parent_alert() returns trigger
language plpgsql security definer set search_path = '' as $$
declare v_child text; v_where text; v_ctx text;
begin
  if new.kind not in ('environment_left', 'domain_blocked') then return null; end if;
  select full_name into v_child from public.users where id = new.student_id;
  v_ctx := concat_ws(', ', new.lesson_context ->> 'lesson',
                     case when new.lesson_context ? 'slide' then 'slide ' || (new.lesson_context ->> 'slide') end,
                     new.lesson_context ->> 'activity');
  v_where := coalesce(nullif(new.page_title, ''), new.domain);
  perform app.notify(pl.parent_id, 'child_left_lesson',
      coalesce(split_part(v_child, ' ', 1), 'Your child') || ' left ' || coalesce(new.lesson_context ->> 'class', 'a lesson'),
      concat_ws(' · ', new.rule, case when v_where is not null and ts.parent_focus_details then 'went to: ' || v_where end,
                case when v_ctx <> '' then 'during ' || v_ctx end),
      '/parent?child=' || new.student_id || '&period=day', 'warning',
      jsonb_build_object('student_id', new.student_id, 'event_id', new.id))
    from public.parent_links pl
    join public.parent_alert_prefs pr on pr.parent_id = pl.parent_id and pr.student_id = pl.student_id and pr.alert_on_leave
    join public.tenant_settings ts on ts.tenant_id = pl.tenant_id and ts.parent_portal_enabled
   where pl.student_id = new.student_id and pl.revoked_at is null;
  return null;
end$$;
drop trigger if exists environment_events_parent_alert on public.environment_events;
create trigger environment_events_parent_alert after insert on public.environment_events
  for each row execute function app.event_parent_alert();

-- A released grade below a guardian's own threshold.
create or replace function app.grade_parent_alert() returns trigger
language plpgsql security definer set search_path = '' as $$
declare v_student uuid; v_title text; v_points numeric; v_pct numeric;
begin
  if new.released_at is null or (tg_op = 'UPDATE' and old.released_at is not null) then return null; end if;
  select s.student_id, a.title, a.points_possible into v_student, v_title, v_points
    from public.submissions s join public.assignments a on a.id = s.assignment_id where s.id = new.submission_id;
  if v_student is null or coalesce(v_points, 0) <= 0 then return null; end if;
  v_pct := round(100 * new.score / v_points);
  perform app.notify(pl.parent_id, 'child_low_score', 'Grade below ' || pr.low_score_below || '%: ' || v_title,
      v_pct || '% (' || new.score || ' of ' || v_points || '). The teacher''s feedback is in the report.',
      '/parent?child=' || v_student || '&period=week', 'info', jsonb_build_object('student_id', v_student))
    from public.parent_links pl
    join public.parent_alert_prefs pr on pr.parent_id = pl.parent_id and pr.student_id = pl.student_id
    join public.tenant_settings ts on ts.tenant_id = pl.tenant_id and ts.parent_portal_enabled
   where pl.student_id = v_student and pl.revoked_at is null and pr.low_score_below is not null and v_pct < pr.low_score_below;
  return null;
end$$;
drop trigger if exists grades_parent_alert on public.grades;
create trigger grades_parent_alert after insert or update of released_at on public.grades
  for each row execute function app.grade_parent_alert();

-- Weekly summary: Friday from 15:00 in the school's time zone, once a week per guardian and child.
create or replace function app.send_parent_digests() returns int
language plpgsql volatile security definer set search_path = '' as $$
declare r record; v_n int := 0;
begin
  for r in
    select pl.parent_id, pl.student_id, pl.tenant_id, u.full_name
      from public.parent_links pl
      join public.users u on u.id = pl.student_id
      join public.tenants t on t.id = pl.tenant_id
      join public.tenant_settings ts on ts.tenant_id = pl.tenant_id and ts.parent_portal_enabled
      left join public.parent_alert_prefs pr on pr.parent_id = pl.parent_id and pr.student_id = pl.student_id
     where pl.revoked_at is null and coalesce(pr.weekly_digest, true)
       and extract(isodow from now() at time zone t.timezone) = 5
       and extract(hour from now() at time zone t.timezone) >= 15
       and (pr.last_digest_at is null or pr.last_digest_at < now() - interval '6 days')
  loop
    perform app.notify(r.parent_id, 'weekly_report', 'Weekly report for ' || split_part(r.full_name, ' ', 1) || ' is ready',
                       'Lessons, participation, progress by subject and focus for this week.',
                       '/parent?child=' || r.student_id || '&period=week', 'info', jsonb_build_object('student_id', r.student_id));
    insert into public.parent_alert_prefs (parent_id, student_id, tenant_id, last_digest_at)
      values (r.parent_id, r.student_id, r.tenant_id, now())
      on conflict (parent_id, student_id) do update set last_digest_at = now();
    v_n := v_n + 1;
  end loop;
  return v_n;
end$$;

do $$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron;
    perform cron.schedule('swiftcipher-parent-digest', '5 * * * *', 'select app.send_parent_digests()');
  end if;
exception when others then
  raise notice 'pg_cron not scheduled (%). Call app.send_parent_digests() hourly from the maintenance workflow.', sqlerrm;
end$$;

-- ---------------------------------------------------------------------------
-- The report
-- ---------------------------------------------------------------------------
-- Participation 0–100, explained to parents as its parts:
--   30% attendance, 35% answering (5 answers a lesson = full marks), 15% explained
--   reasoning, 5% asking for help, 15% staying focused (each time they left: −25%).
create or replace function app.class_period(p_student uuid, p_class uuid, p_from timestamptz, p_to timestamptz, p_details boolean)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_held int; v_attended int; v_minutes numeric; v_answers int; v_graded int; v_correct int; v_reasoned int;
  v_done int; v_hands int; v_xp int; v_focus int; v_score int;
begin
  select count(*) into v_held from public.class_sessions s
   where s.class_id = p_class and s.started_at >= p_from and s.started_at < p_to;
  select count(*), coalesce(sum(least(greatest(extract(epoch from (
            least(coalesce(p.left_at, s.ended_at, p.last_seen_at), coalesce(s.ended_at, p.last_seen_at)) - p.joined_at)), 0), 14400)) / 60, 0)
    into v_attended, v_minutes
    from public.session_participants p join public.class_sessions s on s.id = p.session_id
   where s.class_id = p_class and p.user_id = p_student and s.started_at >= p_from and s.started_at < p_to;
  select count(*), count(a.is_correct), count(*) filter (where a.is_correct),
         count(*) filter (where length(btrim(coalesce(a.response ->> 'reasoning', ''))) >= 15)
    into v_answers, v_graded, v_correct, v_reasoned
    from public.quiz_answers a join public.quiz_attempts t on t.id = a.attempt_id
   where t.student_id = p_student and app.attempt_class(t) = p_class and a.answered_at >= p_from and a.answered_at < p_to;
  select count(*) into v_done from public.quiz_attempts t
   where t.student_id = p_student and t.status <> 'in_progress' and app.attempt_class(t) = p_class
     and t.submitted_at >= p_from and t.submitted_at < p_to;
  select count(*) into v_hands from public.raise_hands h join public.class_sessions s on s.id = h.session_id
   where s.class_id = p_class and h.student_id = p_student and h.created_at >= p_from and h.created_at < p_to;
  select coalesce(sum(points), 0) into v_xp from public.xp_events
   where student_id = p_student and class_id = p_class and created_at >= p_from and created_at < p_to;
  select count(*) into v_focus from public.environment_events e
   where e.student_id = p_student and e.class_id = p_class and e.created_at >= p_from and e.created_at < p_to
     and e.kind in ('environment_left', 'domain_blocked', 'off_task', 'tab_limit');

  if v_held > 0 or v_answers > 0 then
    v_score := round(100 * (
        0.30 * case when v_held > 0 then least(v_attended::numeric / v_held, 1) else 1 end
      + 0.35 * least(v_answers::numeric / (5 * greatest(v_attended, 1)), 1)
      + 0.15 * case when v_answers > 0 then v_reasoned::numeric / v_answers else 0 end
      + 0.05 * least(v_hands::numeric / greatest(v_attended, 1), 1)
      + 0.15 * greatest(0, 1 - 0.25 * v_focus)));
  end if;

  return jsonb_build_object(
    'sessions_held', v_held, 'sessions_attended', v_attended, 'minutes', round(v_minutes),
    'answers', v_answers, 'accuracy', case when v_graded > 0 then round(100.0 * v_correct / v_graded) end,
    'reasoned', v_reasoned, 'activities_completed', v_done, 'hands_raised', v_hands, 'xp', v_xp,
    'focus_events', v_focus, 'participation', v_score,
    'focus', case when not p_details then '[]'::jsonb else (
      select coalesce(jsonb_agg(jsonb_build_object(
          'at', e.away_started_at, 'kind', e.kind, 'reason', e.rule, 'site', e.domain, 'page_title', e.page_title,
          'context', e.lesson_context, 'returned', e.resolved_at is not null,
          'away_minutes', case when e.resolved_at is not null
                               then greatest(1, round(extract(epoch from (e.resolved_at - coalesce(e.away_started_at, e.created_at))) / 60)) end)
          order by e.created_at desc), '[]'::jsonb)
      from (select * from public.environment_events e
             where e.student_id = p_student and e.class_id = p_class and e.created_at >= p_from and e.created_at < p_to
               and e.kind in ('environment_left', 'domain_blocked', 'off_task', 'tab_limit')
             order by e.created_at desc limit 25) e) end);
end$$;

create or replace function public.parent_report(p_student uuid, p_period text default 'week', p_date date default null)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_student public.users; v_tz text; v_day date; v_from timestamptz; v_to timestamptz; v_span interval;
  v_details boolean; v_subjects jsonb;
begin
  select * into v_student from public.users where id = p_student;
  if v_student.id is null or not (app.is_parent_of(p_student) or app.teaches_student(p_student)
                                  or (app.is_admin() and v_student.tenant_id = app.tenant_id())) then
    raise exception 'Report not found.' using errcode = 'P0002';
  end if;
  if p_period not in ('day', 'week') then raise exception 'Period is day or week.' using errcode = '22023'; end if;
  select t.timezone, ts.parent_focus_details into v_tz, v_details
    from public.tenants t join public.tenant_settings ts on ts.tenant_id = t.id where t.id = v_student.tenant_id;
  v_tz := coalesce(v_tz, 'UTC');
  v_day := coalesce(p_date, (now() at time zone v_tz)::date);
  if p_period = 'week' then v_day := v_day - (extract(isodow from v_day)::int - 1); v_span := interval '7 days';
  else v_span := interval '1 day'; end if;
  v_from := v_day::timestamp at time zone v_tz;
  v_to := v_from + v_span;
  -- Staff always see details; parents as the school decides.
  v_details := coalesce(v_details, true) or not app.is_parent_of(p_student);

  select coalesce(jsonb_agg(x order by x ->> 'class'), '[]'::jsonb) into v_subjects from (
    select jsonb_build_object(
        'class_id', c.id, 'class', c.name, 'subject', c.subject, 'teacher', tu.full_name, 'teacher_id', c.teacher_id,
        'now', app.class_period(p_student, c.id, v_from, v_to, v_details),
        'before', app.class_period(p_student, c.id, v_from - v_span, v_from, false) - 'focus',
        -- Six weeks ending with this one, for the learning-progress chart.
        'trend', (select coalesce(jsonb_agg(jsonb_build_object('week', (w at time zone v_tz)::date,
                      'accuracy', cp -> 'accuracy', 'xp', cp -> 'xp', 'participation', cp -> 'participation') order by w), '[]'::jsonb)
                  from generate_series((date_trunc('week', v_from at time zone v_tz) - interval '5 weeks') at time zone v_tz,
                                       date_trunc('week', v_from at time zone v_tz) at time zone v_tz, interval '7 days') w
                  cross join lateral (select app.class_period(p_student, c.id, w, w + interval '7 days', false) as cp) z),
        'assignments', (select jsonb_build_object(
              'due', count(*),
              'submitted', count(*) filter (where exists (select 1 from public.submissions s where s.assignment_id = a.id and s.student_id = p_student)),
              'late', count(*) filter (where exists (select 1 from public.submissions s where s.assignment_id = a.id and s.student_id = p_student and s.is_late)),
              'missing', count(*) filter (where a.due_at < now() and not exists (select 1 from public.submissions s where s.assignment_id = a.id and s.student_id = p_student)),
              'missing_titles', coalesce(jsonb_agg(a.title) filter (where a.due_at < now() and not exists (
                  select 1 from public.submissions s where s.assignment_id = a.id and s.student_id = p_student)), '[]'::jsonb))
            from public.assignments a
           where a.class_id = c.id and a.status <> 'draft' and a.due_at >= v_from and a.due_at < v_to),
        'grades', (select coalesce(jsonb_agg(jsonb_build_object('assignment', a.title, 'score', g.score, 'out_of', a.points_possible,
                      'feedback', g.feedback, 'released_at', g.released_at) order by g.released_at desc), '[]'::jsonb)
                   from public.grades g join public.submissions s on s.id = g.submission_id join public.assignments a on a.id = s.assignment_id
                   where a.class_id = c.id and s.student_id = p_student and g.released_at >= v_from and g.released_at < v_to)) as x
    from public.class_members m
    join public.classes c on c.id = m.class_id
    left join public.users tu on tu.id = c.teacher_id
    where m.user_id = p_student and m.role = 'student') q;

  return jsonb_build_object(
    'student', jsonb_build_object('id', v_student.id, 'name', v_student.full_name),
    'period', p_period, 'from', v_from, 'to', v_to, 'date', v_day, 'timezone', v_tz, 'focus_details', v_details,
    'progress', (select jsonb_build_object('xp', coalesce(sum(points), 0), 'level', app.xp_level(coalesce(sum(points), 0)))
                 from public.xp_events where student_id = p_student),
    'badges', (select coalesce(jsonb_agg(jsonb_build_object('badge', b.badge, 'earned_at', b.earned_at) order by b.earned_at), '[]'::jsonb)
               from public.student_badges b where b.student_id = p_student and b.earned_at >= v_from and b.earned_at < v_to),
    'subjects', v_subjects);
end$$;

-- ---------------------------------------------------------------------------
-- Parent ↔ teacher messages about a child (the child can't see them)
-- ---------------------------------------------------------------------------
alter table public.chat_threads add column if not exists parent_id uuid;
do $$ begin
  alter table public.chat_threads add constraint chat_threads_parent_fkey
    foreign key (parent_id, tenant_id) references public.users(id, tenant_id) on delete cascade;
exception when duplicate_object then null; end $$;
create index if not exists chat_threads_parent_idx on public.chat_threads(parent_id) where parent_id is not null;
alter table public.chat_threads drop constraint if exists chat_threads_kind_check;
alter table public.chat_threads drop constraint if exists chat_threads_check;
alter table public.chat_threads drop constraint if exists chat_threads_shape_check;
alter table public.chat_threads add constraint chat_threads_shape_check check (
     (kind = 'direct' and student_id is not null and teacher_id is not null and parent_id is null)
  or (kind = 'group' and session_id is not null and parent_id is null)
  or (kind = 'parent' and student_id is not null and teacher_id is not null and parent_id is not null));
create unique index if not exists chat_threads_parent_uidx on public.chat_threads(class_id, student_id, teacher_id, parent_id) where kind = 'parent';

drop policy if exists chat_threads_read on public.chat_threads;
create policy chat_threads_read on public.chat_threads for select to authenticated
  using (tenant_id = (select app.tenant_id())
         and ((kind = 'direct' and (student_id = (select auth.uid()) or teacher_id = (select auth.uid())))
              or (kind = 'parent' and (parent_id = (select auth.uid()) or teacher_id = (select auth.uid())))
              or (kind = 'group' and (app.can_manage_class(class_id) or app.in_class(class_id)))));

create or replace function public.open_parent_thread(p_student uuid, p_class uuid, p_parent uuid default null) returns uuid
language plpgsql volatile security definer set search_path = '' as $$
declare v_me public.users := app.me(); v_teacher uuid; v_parent uuid; v_id uuid;
begin
  if not exists (select 1 from public.class_members where class_id = p_class and user_id = p_student and role = 'student') then
    raise exception 'That child is not in this class.' using errcode = 'P0002';
  end if;
  if v_me.role = 'parent' then
    if not app.is_parent_of(p_student) then raise exception 'Not your child.' using errcode = '42501'; end if;
    v_parent := v_me.id;
    select teacher_id into v_teacher from public.classes where id = p_class;
  elsif app.can_manage_class(p_class) and v_me.role <> 'student' then
    v_teacher := v_me.id; v_parent := p_parent;
    if not exists (select 1 from public.parent_links where parent_id = p_parent and student_id = p_student and revoked_at is null) then
      raise exception 'That parent is not linked to this child.' using errcode = 'P0002';
    end if;
  else
    raise exception 'Not your class.' using errcode = '42501';
  end if;
  select id into v_id from public.chat_threads
   where class_id = p_class and kind = 'parent' and student_id = p_student and teacher_id = v_teacher and parent_id = v_parent;
  if v_id is null then
    insert into public.chat_threads (tenant_id, class_id, kind, student_id, teacher_id, parent_id)
      values (v_me.tenant_id, p_class, 'parent', p_student, v_teacher, v_parent) returning id into v_id;
  end if;
  return v_id;
end$$;

create or replace function public.send_message(p_thread uuid, p_body text) returns uuid
language plpgsql volatile security definer set search_path = '' as $$
declare v_me public.users := app.me(); v_t public.chat_threads; v_id uuid; v_to uuid; v_link text;
begin
  select * into v_t from public.chat_threads where id = p_thread and tenant_id = v_me.tenant_id;
  if v_t.id is null then raise exception 'Conversation not found.' using errcode = 'P0002'; end if;
  if length(btrim(coalesce(p_body, ''))) not between 1 and 2000 then raise exception 'Messages are 1-2000 characters.' using errcode = '22023'; end if;
  if v_t.kind = 'direct' then
    if v_me.id not in (v_t.student_id, v_t.teacher_id) then raise exception 'Not your conversation.' using errcode = '42501'; end if;
    v_to := case when v_me.id = v_t.student_id then v_t.teacher_id else v_t.student_id end;
    v_link := '/messages?thread=' || p_thread;
  elsif v_t.kind = 'parent' then
    if v_me.id not in (v_t.parent_id, v_t.teacher_id) then raise exception 'Not your conversation.' using errcode = '42501'; end if;
    if v_me.id = v_t.parent_id and not app.is_parent_of(v_t.student_id) then raise exception 'Not your child.' using errcode = '42501'; end if;
    v_to := case when v_me.id = v_t.parent_id then v_t.teacher_id else v_t.parent_id end;
    v_link := case when v_me.id = v_t.parent_id then '/messages?thread=' || p_thread
                   else '/parent?child=' || v_t.student_id || '&thread=' || p_thread end;
  else
    if not (app.can_manage_class(v_t.class_id)
            or (app.in_class(v_t.class_id) and exists (select 1 from public.class_sessions s where s.id = v_t.session_id
                                                       and s.status = 'live' and s.group_chat_enabled))) then
      raise exception 'Group chat is off for this session.' using errcode = 'P0001';
    end if;
  end if;
  insert into public.chat_messages (tenant_id, thread_id, sender_id, body)
    values (v_me.tenant_id, p_thread, v_me.id, btrim(p_body)) returning id into v_id;
  if v_to is not null then
    perform app.notify(v_to, 'chat_message', 'New message from ' || v_me.full_name, left(btrim(p_body), 140),
                       v_link, 'info', jsonb_build_object('thread_id', p_thread));
  end if;
  return v_id;
end$$;

create or replace function app.can_listen(p_topic text) returns boolean
language plpgsql stable security definer set search_path = '' as $$
declare v_kind text := split_part(p_topic, ':', 1); v_id uuid; v_user uuid;
begin
  begin
    v_id := nullif(split_part(p_topic, ':', 2), '')::uuid;
    v_user := nullif(split_part(p_topic, ':', 3), '')::uuid;
  exception when others then return false; end;
  if v_id is null or app.tenant_id() is null then return false; end if;
  return case v_kind
    when 'session' then app.in_session(v_id) or app.can_manage_session(v_id)
    when 'staff'   then app.can_manage_session(v_id)
    -- teachers watch; the student may join only their own channel (to send frames)
    when 'screen'  then app.can_manage_session(v_id) or (v_user = auth.uid() and app.in_session(v_id))
    when 'user'    then v_id = auth.uid()
    -- parent threads: only the parent and the teacher (never the child, nor other staff)
    when 'thread'  then exists (select 1 from public.chat_threads t where t.id = v_id and t.tenant_id = app.tenant_id()
                                and case when t.kind = 'parent' then auth.uid() in (t.parent_id, t.teacher_id)
                                         else (t.student_id = auth.uid() or t.teacher_id = auth.uid()
                                               or (t.kind = 'group' and app.in_session(t.session_id)) or app.can_manage_class(t.class_id)) end)
    -- boards and games: exactly the people who can read the row (mirrors their RLS policies)
    when 'board'   then exists (select 1 from public.collab_boards b where b.id = v_id and b.tenant_id = app.tenant_id()
                                and (b.owner_id = auth.uid()
                                     or (b.session_id is not null and (app.can_manage_session(b.session_id) or app.in_session(b.session_id)))
                                     or (b.session_id is null and app.is_teacher())))
    when 'game'    then exists (select 1 from public.game_sessions g where g.id = v_id and g.tenant_id = app.tenant_id()
                                and (app.can_manage_class(g.class_id) or app.in_class(g.class_id)))
    when 'annot'   then app.in_session(v_id) or app.can_manage_session(v_id)
    else false end;
end$$;

-- Parents linked to a child in a class (for the teacher's "Message parent").
create or replace function public.class_parents(p_class uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not app.can_manage_class(p_class) then raise exception 'Not your class.' using errcode = '42501'; end if;
  return (select coalesce(jsonb_agg(jsonb_build_object('student_id', pl.student_id, 'parent_id', pl.parent_id,
                    'parent', pu.full_name, 'relation', pl.relation) order by pu.full_name), '[]'::jsonb)
          from public.parent_links pl join public.class_members m on m.user_id = pl.student_id and m.class_id = p_class and m.role = 'student'
          join public.users pu on pu.id = pl.parent_id
          where pl.revoked_at is null);
end$$;

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------
revoke execute on function public.parent_report(uuid, text, date), public.parent_alerts(uuid),
  public.set_parent_alerts(uuid, boolean, boolean, int), public.open_parent_thread(uuid, uuid, uuid), public.class_parents(uuid),
  app.class_period(uuid, uuid, timestamptz, timestamptz, boolean), app.send_parent_digests()
  from public, anon;
grant execute on function public.parent_report(uuid, text, date), public.parent_alerts(uuid),
  public.set_parent_alerts(uuid, boolean, boolean, int), public.open_parent_thread(uuid, uuid, uuid), public.class_parents(uuid)
  to authenticated, service_role;
grant execute on function app.send_parent_digests() to service_role;

create or replace function public.health() returns jsonb
language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('ok', true, 'db_time', now(), 'schema', '0820')
$$;

-- =============================================================================
-- SwiftCipher — 0830 fixes from the 2026-09-27 penetration test
--
-- 1. Paid-feature bypass (confirmed live). A school's own feature flag took
--    precedence over its plan, and school admins can write flags for their
--    school, so an admin on a cheaper plan could switch on paid features
--    (e.g. device control). Now a school's own flag can only switch a feature
--    OFF; turning features on comes from the plan (or a platform-wide flag),
--    and the database refuses "enabled" flags for features the plan lacks.
-- 2. Error-log blinding. The anonymous error endpoint shared one hourly quota
--    with signed-in users, so junk reports could use it up and hide real errors
--    for an hour. Anonymous reports now get their own, smaller share.
-- =============================================================================

create or replace function app.plan_has(p_tenant uuid, p_key text) returns boolean
language sql stable security definer set search_path = '' as $$
  select coalesce(
    (select (p.features ->> p_key)::boolean from public.tenants t join public.plans p on p.code = t.plan_code where t.id = p_tenant),
    (select ff.enabled from public.feature_flags ff where ff.tenant_id is null and ff.key = p_key),
    false)
$$;

create or replace function app.feature(p_tenant uuid, p_key text) returns boolean
language sql stable security definer set search_path = '' as $$
  -- The plan decides; the school may only switch a feature off for itself.
  select app.plan_has(p_tenant, p_key)
     and coalesce((select ff.enabled from public.feature_flags ff where ff.tenant_id = p_tenant and ff.key = p_key), true)
$$;

drop policy if exists feature_flags_admin_write on public.feature_flags;
create policy feature_flags_admin_write on public.feature_flags for all to authenticated
  using (tenant_id = (select app.tenant_id()) and (select app.is_admin()))
  with check (tenant_id = (select app.tenant_id()) and (select app.is_admin())
              and (not enabled or app.plan_has(tenant_id, key)));

create or replace function public.log_error(
  p_source text, p_message text, p_stack text default null, p_url text default null,
  p_user_agent text default null, p_release text default null
) returns void
language plpgsql volatile security definer set search_path = '' as $$
declare v_fp text; v_tenant uuid; v_recent int; v_anon_recent int;
begin
  if p_source not in ('client','server','api') or coalesce(btrim(p_message), '') = '' then return; end if;
  -- Flood guard: at most 600 new rows an hour platform-wide (repeats only bump a counter),
  -- of which anonymous callers may use 150, so they can't crowd out real errors.
  select count(*), count(*) filter (where user_id is null) into v_recent, v_anon_recent
    from public.error_events where first_seen_at > now() - interval '1 hour';
  v_fp := md5(p_source || '|' || left(p_message, 300) || '|' || coalesce(left(split_part(coalesce(p_stack, ''), E'\n', 2), 300), ''));
  begin v_tenant := app.tenant_id(); exception when others then v_tenant := null; end;
  update public.error_events set count = count + 1, last_seen_at = now(),
         url = coalesce(left(p_url, 2000), url), tenant_id = coalesce(v_tenant, tenant_id)
   where fingerprint = v_fp and resolved_at is null;
  if found or v_recent >= 600 or (auth.uid() is null and v_anon_recent >= 150) then return; end if;
  insert into public.error_events (fingerprint, source, message, stack, url, user_agent, release, tenant_id, user_id)
    values (v_fp, p_source, left(p_message, 2000), left(p_stack, 8000), left(p_url, 2000), left(p_user_agent, 500),
            left(p_release, 100), v_tenant, auth.uid())
    on conflict (fingerprint) where resolved_at is null do update set count = public.error_events.count + 1, last_seen_at = now();
end$$;

revoke execute on function app.plan_has(uuid, text) from public, anon;
grant execute on function app.plan_has(uuid, text) to authenticated, service_role;

create or replace function public.health() returns jsonb
language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('ok', true, 'db_time', now(), 'schema', '0830')
$$;

-- =============================================================================
-- Done. One row: schema should be 0830 and every other column true.
-- =============================================================================
select public.health() ->> 'schema' as schema,
       exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'student_supports') as fair_play_ready,
       exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'code_attempts') as code_guessing_blocked,
       exists (select 1 from information_schema.routines where routine_schema = 'public' and routine_name = 'reorder_slides') as slide_order_ready,
       exists (select 1 from information_schema.routines where routine_schema = 'public' and routine_name = 'parent_report') as parent_reports_ready,
       exists (select 1 from information_schema.columns where table_name = 'chat_threads' and column_name = 'parent_id') as parent_messages_ready,
       exists (select 1 from information_schema.routines where routine_schema = 'app' and routine_name = 'plan_has') as paid_features_protected;
