-- =============================================================================
-- SwiftCipher update 2026-09-26: fair play (migration 0800).
--   * Answers lock once the correct answer is shown; optional second chance
--     for half credit (redemption questions).
--   * Untimed, accuracy-first games; class goal mode; lock a game's lobby.
--   * Private learning supports per student: read aloud, easy-to-read font,
--     extra time, calm mode.
--   * Students write quiz questions; teachers approve them (XP + badge).
--   * Class gradebook export.
--
-- For a database that already ran supabase/updates/2026-09-25_classroom_update.sql.
-- Safe to run more than once. Generated by scripts/build-update-sql.mjs.
-- Supabase dashboard -> SQL Editor -> New query -> paste all -> Run.
-- =============================================================================

-- =============================================================================
-- SwiftCipher — 0800 fair play: what teachers complain about in Kahoot, Blooket,
-- Gimkit, Wayground (Quizizz) and Nearpod, fixed; what they love, included.
--
-- Answers are locked once revealed. With instant feedback a student could see
--   the correct answer and resubmit it for full marks; now a revealed answer is
--   final. Optional "second chance" (Wayground's redemption questions): a wrong
--   answer may be tried once more for half credit, and the correct answer is
--   only shown after that second try.
-- Accuracy over speed (the top complaint about Kahoot): games can run untimed,
--   with no speed bonus, so careful thinkers and English learners are not
--   punished. A "class goal" mode makes the whole class work together towards
--   one target instead of ranking children against each other.
-- Lock the game (Kahoot's lobby lock): no one else can join once the teacher
--   has started, and players stay signed-in students of the class (no bots).
-- Learning supports (Wayground's accommodations), set privately per student:
--   read aloud, easy-to-read font, extra time on timed work, calm mode.
-- Students write questions (Gimkit's KitCollab): the teacher opens a quiz for
--   question writing, students submit questions with an explanation, the
--   teacher approves them into the quiz; approved authors earn XP and a badge.
-- Gradebook export (a Nearpod complaint): one CSV per class, every student and
--   every assignment.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------
alter table public.quiz_answers
  add column if not exists tries smallint not null default 1 check (tries between 1 and 2),
  add column if not exists revealed boolean not null default false;

create table if not exists public.student_supports (
  student_id      uuid primary key,
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  read_aloud      boolean not null default false,
  readable_font   boolean not null default false,
  extra_time_pct  smallint not null default 0 check (extra_time_pct in (0, 25, 50, 100)),
  calm_mode       boolean not null default false,
  note            text check (length(note) <= 500),   -- staff only, never shown to the student
  updated_by      uuid,
  updated_at      timestamptz not null default now(),
  foreign key (student_id, tenant_id) references public.users(id, tenant_id) on delete cascade
);
create index if not exists student_supports_tenant_idx on public.student_supports(tenant_id);

create table if not exists public.question_collabs (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  class_id    uuid not null,
  activity_id uuid not null,
  opened_by   uuid not null,
  is_open     boolean not null default true,
  prompt      text check (length(prompt) <= 500),    -- what the teacher wants questions about
  created_at  timestamptz not null default now(),
  unique (class_id, activity_id),
  unique (id, tenant_id),
  foreign key (class_id, tenant_id) references public.classes(id, tenant_id) on delete cascade,
  foreign key (activity_id, tenant_id) references public.activities(id, tenant_id) on delete cascade,
  foreign key (opened_by, tenant_id) references public.users(id, tenant_id) deferrable initially deferred
);
create index if not exists question_collabs_activity_idx on public.question_collabs(activity_id);
create index if not exists question_collabs_tenant_idx on public.question_collabs(tenant_id);

create table if not exists public.question_submissions (
  id           uuid primary key default gen_random_uuid(),
  tenant_id    uuid not null references public.tenants(id) on delete cascade,
  collab_id    uuid not null,
  student_id   uuid not null,
  prompt       text not null check (length(btrim(prompt)) between 5 and 1000),
  options      jsonb not null,             -- [{ "label": text, "correct": bool }], 2–6 items, exactly one correct
  explanation  text not null check (length(btrim(explanation)) between 10 and 1000),
  status       text not null default 'pending' check (status in ('pending','approved','returned')),
  feedback     text check (length(feedback) <= 1000),
  question_id  uuid,
  reviewed_by  uuid,
  reviewed_at  timestamptz,
  created_at   timestamptz not null default now(),
  unique (id, tenant_id),
  foreign key (collab_id, tenant_id) references public.question_collabs(id, tenant_id) on delete cascade,
  foreign key (student_id, tenant_id) references public.users(id, tenant_id) on delete cascade,
  foreign key (question_id) references public.questions(id) on delete set null (question_id),
  foreign key (reviewed_by) references public.users(id) on delete set null (reviewed_by)
);
create index if not exists question_submissions_collab_idx on public.question_submissions(collab_id, status);
create index if not exists question_submissions_student_idx on public.question_submissions(student_id);
create index if not exists question_submissions_tenant_idx on public.question_submissions(tenant_id);
create index if not exists question_submissions_question_idx on public.question_submissions(question_id) where question_id is not null;
create index if not exists question_submissions_reviewer_idx on public.question_submissions(reviewed_by) where reviewed_by is not null;
create index if not exists question_collabs_opened_by_idx on public.question_collabs(opened_by);

-- XP and a badge for approved questions.
alter table public.xp_events drop constraint if exists xp_events_source_check;
alter table public.xp_events add constraint xp_events_source_check
  check (source in ('answer','reasoning','completion','perfect','game','teacher','question'));
alter table public.student_badges drop constraint if exists student_badges_badge_check;
alter table public.student_badges add constraint student_badges_badge_check
  check (badge in ('first_steps','rising_star','scholar','deep_thinker','perfectionist','challenger','shout_out','game_on','author'));

-- Reads go through RPCs; students may read their own supports and submissions directly.
alter table public.student_supports enable row level security;
alter table public.question_collabs enable row level security;
alter table public.question_submissions enable row level security;
revoke all on public.student_supports, public.question_collabs, public.question_submissions from anon, authenticated;
grant select on public.student_supports, public.question_collabs, public.question_submissions to authenticated;
drop policy if exists student_supports_read on public.student_supports;
create policy student_supports_read on public.student_supports for select to authenticated
  using (tenant_id = (select app.tenant_id())
         and (student_id = (select auth.uid()) or (select app.is_admin()) or app.teaches_student(student_id)));
drop policy if exists question_collabs_read on public.question_collabs;
create policy question_collabs_read on public.question_collabs for select to authenticated
  using (tenant_id = (select app.tenant_id()) and (app.in_class(class_id) or app.can_manage_class(class_id)));
drop policy if exists question_submissions_read on public.question_submissions;
create policy question_submissions_read on public.question_submissions for select to authenticated
  using (tenant_id = (select app.tenant_id())
         and (student_id = (select auth.uid())
              or exists (select 1 from public.question_collabs c where c.id = collab_id and app.can_manage_class(c.class_id))));

-- ---------------------------------------------------------------------------
-- Badges: add "Question author"
-- ---------------------------------------------------------------------------
create or replace function app.give_badge(p_tenant uuid, p_student uuid, p_badge text) returns void
language plpgsql volatile security definer set search_path = '' as $$
declare v_new boolean;
begin
  insert into public.student_badges (student_id, tenant_id, badge) values (p_student, p_tenant, p_badge)
    on conflict do nothing returning true into v_new;
  if v_new then
    perform app.notify(p_student, 'badge', 'New badge: ' || case p_badge
        when 'first_steps' then 'First steps' when 'rising_star' then 'Rising star' when 'scholar' then 'Scholar'
        when 'deep_thinker' then 'Deep thinker' when 'perfectionist' then 'Perfectionist' when 'challenger' then 'Challenger'
        when 'shout_out' then 'Teacher shout-out' when 'game_on' then 'Game on' when 'author' then 'Question author'
        else p_badge end,
      null, '/student', 'info', jsonb_build_object('badge', p_badge));
  end if;
end$$;

-- ---------------------------------------------------------------------------
-- Answers: locked once revealed; optional second chance for half credit
-- ---------------------------------------------------------------------------
create or replace function public.submit_answer(
  p_attempt uuid, p_question uuid, p_response jsonb, p_elapsed_ms int default null
) returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_me       public.users := app.me();
  v_attempt  public.quiz_attempts;
  v_act      public.activities;
  v_q        public.questions;
  v_prev     public.quiz_answers;
  v_grade    jsonb;
  v_feedback text;
  v_instant  boolean;
  v_second   boolean;
  v_tries    smallint := 1;
  v_score    numeric;
  v_reveal   boolean;
begin
  select * into v_attempt from public.quiz_attempts where id = p_attempt and student_id = v_me.id for update;
  if v_attempt.id is null then raise exception 'Attempt not found.' using errcode = 'P0002'; end if;
  if v_attempt.status <> 'in_progress' then raise exception 'This attempt has already been submitted.' using errcode = 'P0001'; end if;
  if v_attempt.deadline_at is not null and now() > v_attempt.deadline_at + interval '5 seconds' then
    perform public.finish_attempt(p_attempt);
    raise exception 'Time is up — your attempt was submitted.' using errcode = 'P0001';
  end if;
  if length(p_response::text) > 200000 then raise exception 'Response is too large.' using errcode = '22023'; end if;

  select * into v_q from public.questions where id = p_question and activity_id = v_attempt.activity_id;
  if v_q.id is null then raise exception 'Question not in this activity.' using errcode = 'P0002'; end if;
  select * into v_act from public.activities where id = v_attempt.activity_id;
  v_feedback := coalesce(v_act.settings ->> 'show_feedback', 'after_submit');
  v_second := coalesce((v_act.settings ->> 'redemption')::boolean, false);
  v_grade := app.grade_response(v_q, p_response);
  v_instant := v_feedback = 'immediately' and v_grade ->> 'status' = 'auto_graded';
  v_score := (v_grade ->> 'score')::numeric;

  select * into v_prev from public.quiz_answers where attempt_id = p_attempt and question_id = p_question;
  if v_prev.id is not null then
    -- Once the correct answer has been shown, the answer is final.
    if v_prev.revealed then
      raise exception 'You have already answered this question. Move on to the next one.' using errcode = 'P0001';
    end if;
    -- Second chance: only after a wrong first try with instant feedback. Worth half.
    if v_instant and v_second and v_prev.is_correct is false and v_prev.tries = 1 then
      v_tries := 2;
      v_score := round(coalesce(v_score, 0) * 0.5, 2);
    end if;
  end if;

  -- With a second chance on, a wrong first try says "not quite" without showing the answer.
  v_reveal := v_instant and not (v_second and v_tries = 1 and (v_grade ->> 'is_correct')::boolean is false);

  insert into public.quiz_answers (tenant_id, attempt_id, question_id, response, is_correct, auto_score, status, elapsed_ms, tries, revealed)
    values (v_me.tenant_id, p_attempt, p_question, p_response, (v_grade ->> 'is_correct')::boolean,
            v_score, v_grade ->> 'status', greatest(coalesce(p_elapsed_ms, 0), 0), v_tries, v_reveal)
    on conflict (attempt_id, question_id) do update
      set response = excluded.response, is_correct = excluded.is_correct, auto_score = excluded.auto_score,
          status = excluded.status, elapsed_ms = excluded.elapsed_ms, answered_at = now(),
          tries = excluded.tries, revealed = excluded.revealed;

  if v_instant and v_reveal then
    return jsonb_build_object('saved', true, 'status', v_grade ->> 'status', 'tries', v_tries,
                              'is_correct', (v_grade ->> 'is_correct')::boolean, 'score', v_score)
           || app.reveal_answer(v_q);
  elsif v_instant then
    return jsonb_build_object('saved', true, 'status', v_grade ->> 'status', 'tries', v_tries,
                              'is_correct', false, 'second_chance', true);
  end if;
  return jsonb_build_object('saved', true, 'status', v_grade ->> 'status');
end$$;

-- ---------------------------------------------------------------------------
-- Extra time: start_attempt (0790) with the student's extra-time support applied
-- ---------------------------------------------------------------------------
create or replace function public.start_attempt(
  p_activity uuid, p_session uuid default null, p_assignment uuid default null, p_share text default null
) returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_me       public.users := app.me();
  v_act      public.activities;
  v_attempt  public.quiz_attempts;
  v_allowed  int;
  v_used     int;
  v_limit    int;
  v_extra    int;
  v_shuffle_q boolean;
  v_shuffle_o boolean;
  v_level    smallint;
begin
  select * into v_act from public.activities where id = p_activity and tenant_id = v_me.tenant_id;
  if v_act.id is null then raise exception 'Activity not found.' using errcode = 'P0002'; end if;
  if not app.attempt_context_ok(v_act, p_session, p_assignment, p_share) then
    raise exception 'This activity is not open for you right now.' using errcode = '42501';
  end if;

  -- Resume an unfinished attempt in the same context (§30 reconnect).
  select * into v_attempt from public.quiz_attempts
   where activity_id = p_activity and student_id = v_me.id and status = 'in_progress'
     and session_id is not distinct from p_session and assignment_id is not distinct from p_assignment
   order by attempt_no desc limit 1;

  if v_attempt.id is null then
    if coalesce((v_act.settings ->> 'differentiate')::boolean, false) then
      select coalesce(m.level, 2) into v_level from public.class_members m
       where m.user_id = v_me.id and m.role = 'student'
         and m.class_id = coalesce((select s.class_id from public.class_sessions s where s.id = p_session),
                                   (select a.class_id from public.assignments a where a.id = p_assignment));
      v_level := coalesce(v_level, 2);
      if not exists (select 1 from public.questions q where q.activity_id = p_activity and app.question_in_level(q.difficulty, v_level)) then
        v_level := null;
      end if;
    end if;
    v_allowed := coalesce((v_act.settings ->> 'attempts_allowed')::int, 1);
    select coalesce(max(attempt_no), 0) into v_used from public.quiz_attempts
     where activity_id = p_activity and student_id = v_me.id
       and session_id is not distinct from p_session and assignment_id is not distinct from p_assignment;
    if v_allowed > 0 and v_used >= v_allowed then
      raise exception 'No attempts left for this activity.' using errcode = 'P0001';
    end if;
    v_limit := nullif((v_act.settings ->> 'time_limit_seconds')::int, 0);
    select coalesce(extra_time_pct, 0) into v_extra from public.student_supports where student_id = v_me.id;
    if v_limit is not null and coalesce(v_extra, 0) > 0 then
      v_limit := v_limit + (v_limit * v_extra / 100);
    end if;
    insert into public.quiz_attempts (tenant_id, activity_id, student_id, session_id, assignment_id,
                                      attempt_no, seed, deadline_at, max_score, level)
      values (v_me.tenant_id, p_activity, v_me.id, p_session, p_assignment, v_used + 1,
              (random() * 2147483646)::int,
              case when v_limit is null then null else now() + make_interval(secs => v_limit) end,
              (select coalesce(sum(points), 0) from public.questions
                where activity_id = p_activity and kind <> 'poll' and app.question_in_level(difficulty, v_level)),
              v_level)
      returning * into v_attempt;
  end if;

  v_shuffle_q := coalesce((v_act.settings ->> 'shuffle_questions')::boolean, false);
  v_shuffle_o := coalesce((v_act.settings ->> 'shuffle_options')::boolean, false);

  return jsonb_build_object(
    'attempt', jsonb_build_object('id', v_attempt.id, 'attempt_no', v_attempt.attempt_no,
                                  'deadline_at', v_attempt.deadline_at, 'status', v_attempt.status,
                                  'server_now', now(), 'level', v_attempt.level),
    'activity', jsonb_build_object('id', v_act.id, 'kind', v_act.kind, 'title', v_act.title,
                                   'instructions', v_act.instructions, 'settings', v_act.settings - 'rubric_id'),
    'questions', (select coalesce(jsonb_agg(app.sanitize_question(q, v_attempt.seed, v_shuffle_o)
                                   order by case when v_shuffle_q then app.shuffle_key(v_attempt.seed, q.id::text)
                                                 else lpad(q.position::text, 6, '0') || q.created_at::text end), '[]'::jsonb)
                  from public.questions q where q.activity_id = p_activity and app.question_in_level(q.difficulty, v_attempt.level)),
    'answers', (select coalesce(jsonb_object_agg(a.question_id, a.response), '{}'::jsonb)
                from public.quiz_answers a where a.attempt_id = v_attempt.id),
    -- Which answers are final (already revealed) and which are on their second try.
    'locked', (select coalesce(jsonb_object_agg(a.question_id, jsonb_build_object('revealed', a.revealed, 'tries', a.tries, 'is_correct', a.is_correct)), '{}'::jsonb)
               from public.quiz_answers a where a.attempt_id = v_attempt.id and (a.revealed or a.tries > 1 or a.is_correct is false)));
end$$;

-- ---------------------------------------------------------------------------
-- Games: untimed (accuracy first), class goal, lobby lock
-- ---------------------------------------------------------------------------
create or replace function app.game_settings(p jsonb) returns jsonb
language sql immutable set search_path = '' as $$
  select jsonb_build_object(
    -- 0 = untimed: the teacher moves on when the class is ready; no speed bonus.
    'question_seconds', case when coalesce((p ->> 'question_seconds')::int, 20) = 0 then 0
                             else least(greatest(coalesce((p ->> 'question_seconds')::int, 20), 5), 240) end,
    'speed_bonus',      coalesce((p ->> 'speed_bonus')::boolean, true) and coalesce((p ->> 'question_seconds')::int, 20) <> 0,
    'streak_bonus',     coalesce((p ->> 'streak_bonus')::boolean, true),
    'rank_visibility',  case when coalesce((p ->> 'class_goal')::boolean, false) then 'hidden'
                             when p ->> 'rank_visibility' in ('after_each','end_only','hidden') then p ->> 'rank_visibility' else 'after_each' end,
    'display_mode',     case when p ->> 'display_mode' in ('first_name_initial','nickname','anonymous') then p ->> 'display_mode' else 'first_name_initial' end,
    'team_mode',        coalesce((p ->> 'team_mode')::boolean, false),
    'team_count',       least(greatest(coalesce((p ->> 'team_count')::int, 2), 2), 6),
    'shuffle_questions', coalesce((p ->> 'shuffle_questions')::boolean, false),
    'shuffle_options',  coalesce((p ->> 'shuffle_options')::boolean, true),
    'podium_size',      least(greatest(coalesce((p ->> 'podium_size')::int, 3), 1), 10),
    'certificates',     coalesce((p ->> 'certificates')::boolean, true),
    -- Whole class works towards one target: this share of all answers correct.
    'class_goal',       coalesce((p ->> 'class_goal')::boolean, false),
    'goal_percent',     least(greatest(coalesce((p ->> 'goal_percent')::int, 70), 30), 100),
    'locked',           coalesce((p ->> 'locked')::boolean, false))
$$;

create or replace function app.open_question(p_game public.game_sessions, p_index int) returns void
language sql volatile security definer set search_path = '' as $$
  update public.game_sessions set status = 'question', current_index = p_index,
    question_started_at = now(),
    -- Untimed questions stay open (up to an hour) until everyone answers or the teacher moves on.
    question_ends_at = now() + case when (p_game.settings ->> 'question_seconds')::int = 0 then interval '1 hour'
                                    else make_interval(secs => (p_game.settings ->> 'question_seconds')::int) end,
    started_at = coalesce(started_at, now())
  where id = p_game.id
$$;

create or replace function public.join_game(p_code text, p_nickname text default null) returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_me     public.users := app.me();
  v_game   public.game_sessions;
  v_name   text;
  v_team   uuid;
  v_player public.game_players;
  v_n      int;
begin
  select * into v_game from public.game_sessions where join_code = upper(btrim(p_code)) and status <> 'ended';
  if v_game.id is null then raise exception 'No open game with that code.' using errcode = 'P0002'; end if;
  if not app.in_class(v_game.class_id) or v_me.role <> 'student' then
    raise exception 'This game is for students in another class.' using errcode = '42501';
  end if;

  select * into v_player from public.game_players where game_id = v_game.id and user_id = v_me.id;
  if v_player.id is not null then return jsonb_build_object('game_id', v_game.id, 'player_id', v_player.id, 'display_name', v_player.display_name); end if;
  if coalesce((v_game.settings ->> 'locked')::boolean, false) then
    raise exception 'Your teacher has locked this game. Ask them to let you in.' using errcode = 'P0001';
  end if;

  case v_game.settings ->> 'display_mode'
    when 'nickname' then
      v_name := regexp_replace(btrim(coalesce(p_nickname, '')), '\s+', ' ', 'g');
      if v_name !~ '^[A-Za-z0-9][A-Za-z0-9 _-]{1,19}$' then
        raise exception 'Nicknames are 2-20 letters, numbers, spaces, - or _.' using errcode = '22023';
      end if;
      if exists (select 1 from public.game_players where game_id = v_game.id and lower(display_name) = lower(v_name)) then
        raise exception 'That nickname is taken in this game.' using errcode = 'P0001';
      end if;
    when 'anonymous' then
      select count(*) + 1 into v_n from public.game_players where game_id = v_game.id;
      v_name := 'Player ' || v_n;
    else
      v_name := app.display_name(v_me.full_name);
  end case;

  if (v_game.settings ->> 'team_mode')::boolean then
    select t.id into v_team from public.game_teams t
      left join public.game_players p on p.team_id = t.id
     where t.game_id = v_game.id group by t.id order by count(p.id), t.name limit 1;
  end if;

  insert into public.game_players (tenant_id, game_id, user_id, display_name, team_id)
    values (v_me.tenant_id, v_game.id, v_me.id, v_name, v_team) returning * into v_player;
  return jsonb_build_object('game_id', v_game.id, 'player_id', v_player.id, 'display_name', v_player.display_name);
end$$;

create or replace function public.game_control(p_game uuid, p_action text) returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare v public.game_sessions := app.require_game_host(p_game); v_total int;
begin
  v_total := coalesce(array_length(v.question_order, 1), 0);
  case p_action
    when 'start' then
      if v.status <> 'lobby' then raise exception 'The game has already started.' using errcode = 'P0001'; end if;
      perform app.open_question(v, 0);
    when 'close' then
      perform app.close_question(p_game);
    when 'next' then
      if v.status = 'question' then perform app.close_question(p_game); end if;
      if v.current_index + 1 >= v_total then perform app.finish_game(p_game);
      else perform app.open_question(v, v.current_index + 1); end if;
    when 'end' then
      perform app.finish_game(p_game);
    when 'lock' then
      update public.game_sessions set settings = settings || '{"locked": true}'::jsonb where id = p_game;
    when 'unlock' then
      update public.game_sessions set settings = settings || '{"locked": false}'::jsonb where id = p_game;
    else raise exception 'Unknown action.' using errcode = '22023';
  end case;
  perform app.audit('game.' || p_action, 'game', p_game::text);
  select * into v from public.game_sessions where id = p_game;
  return jsonb_build_object('status', v.status, 'current_index', v.current_index, 'locked', coalesce((v.settings ->> 'locked')::boolean, false));
end$$;

-- Class goal progress, for the host and every player.
create or replace function public.game_goal(p_game uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v public.game_sessions; v_players int; v_asked int; v_correct int;
begin
  select * into v from public.game_sessions where id = p_game;
  if v.id is null then raise exception 'Game not found.' using errcode = 'P0002'; end if;
  if not app.can_manage_class(v.class_id) and not app.in_class(v.class_id) then raise exception 'Not your game.' using errcode = '42501'; end if;
  select count(*) into v_players from public.game_players where game_id = p_game;
  v_asked := greatest(v.current_index + 1, 0);
  select count(*) into v_correct from public.game_answers where game_id = p_game and is_correct;
  return jsonb_build_object('enabled', coalesce((v.settings ->> 'class_goal')::boolean, false),
    'correct', v_correct,
    'target', ceil(v_players * coalesce(array_length(v.question_order, 1), 0) * (v.settings ->> 'goal_percent')::numeric / 100),
    'possible_so_far', v_players * v_asked,
    'goal_percent', (v.settings ->> 'goal_percent')::int);
end$$;

-- ---------------------------------------------------------------------------
-- Learning supports (accommodations), set privately by the student's teachers
-- ---------------------------------------------------------------------------
create or replace function public.set_student_supports(
  p_class uuid, p_student uuid, p_read_aloud boolean, p_readable_font boolean, p_extra_time_pct int,
  p_calm_mode boolean, p_note text default null
) returns void
language plpgsql volatile security definer set search_path = '' as $$
declare v_me public.users := app.me();
begin
  if not app.can_manage_class(p_class) then raise exception 'Not your class.' using errcode = '42501'; end if;
  if not exists (select 1 from public.class_members where class_id = p_class and user_id = p_student and role = 'student') then
    raise exception 'That student is not in this class.' using errcode = 'P0002';
  end if;
  if coalesce(p_extra_time_pct, 0) not in (0, 25, 50, 100) then
    raise exception 'Extra time is 0, 25, 50 or 100 percent.' using errcode = '22023';
  end if;
  insert into public.student_supports (student_id, tenant_id, read_aloud, readable_font, extra_time_pct, calm_mode, note, updated_by, updated_at)
    values (p_student, v_me.tenant_id, coalesce(p_read_aloud, false), coalesce(p_readable_font, false),
            coalesce(p_extra_time_pct, 0), coalesce(p_calm_mode, false), nullif(btrim(coalesce(p_note, '')), ''), v_me.id, now())
    on conflict (student_id) do update set read_aloud = excluded.read_aloud, readable_font = excluded.readable_font,
      extra_time_pct = excluded.extra_time_pct, calm_mode = excluded.calm_mode, note = excluded.note,
      updated_by = excluded.updated_by, updated_at = now();
  perform app.audit('student.supports_set', 'user', p_student::text,
    jsonb_build_object('class_id', p_class, 'read_aloud', p_read_aloud, 'readable_font', p_readable_font,
                       'extra_time_pct', p_extra_time_pct, 'calm_mode', p_calm_mode));
end$$;

create or replace function public.class_supports(p_class uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not app.can_manage_class(p_class) then raise exception 'Not your class.' using errcode = '42501'; end if;
  return (select coalesce(jsonb_agg(jsonb_build_object(
      'student_id', u.id, 'name', u.full_name,
      'read_aloud', coalesce(s.read_aloud, false), 'readable_font', coalesce(s.readable_font, false),
      'extra_time_pct', coalesce(s.extra_time_pct, 0), 'calm_mode', coalesce(s.calm_mode, false), 'note', s.note)
      order by u.full_name), '[]'::jsonb)
    from public.class_members m join public.users u on u.id = m.user_id
    left join public.student_supports s on s.student_id = u.id
    where m.class_id = p_class and m.role = 'student');
end$$;

-- The student's own supports (the staff note is never included).
create or replace function public.my_supports() returns jsonb
language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('read_aloud', coalesce(s.read_aloud, false), 'readable_font', coalesce(s.readable_font, false),
                            'extra_time_pct', coalesce(s.extra_time_pct, 0), 'calm_mode', coalesce(s.calm_mode, false))
  from (select 1) x left join public.student_supports s on s.student_id = auth.uid()
$$;

-- ---------------------------------------------------------------------------
-- Students write questions (teacher approves)
-- ---------------------------------------------------------------------------
create or replace function public.open_question_collab(p_class uuid, p_activity uuid, p_open boolean, p_prompt text default null)
returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare v_me public.users := app.me(); v public.question_collabs; v_title text;
begin
  if not app.can_manage_class(p_class) then raise exception 'Not your class.' using errcode = '42501'; end if;
  select title into v_title from public.activities where id = p_activity and tenant_id = v_me.tenant_id;
  if v_title is null or not app.can_view_activity(p_activity) then raise exception 'Quiz not found.' using errcode = 'P0002'; end if;
  insert into public.question_collabs (tenant_id, class_id, activity_id, opened_by, is_open, prompt)
    values (v_me.tenant_id, p_class, p_activity, v_me.id, p_open, nullif(btrim(coalesce(p_prompt, '')), ''))
    on conflict (class_id, activity_id) do update set is_open = excluded.is_open,
      prompt = coalesce(excluded.prompt, public.question_collabs.prompt)
    returning * into v;
  if p_open then
    perform app.notify(m.user_id, 'question_collab', 'Write a question for ' || v_title,
                       coalesce(v.prompt, 'Your teacher wants your best question. Include the right answer and why.'),
                       '/student', 'info', jsonb_build_object('collab_id', v.id))
    from public.class_members m where m.class_id = p_class and m.role = 'student';
  end if;
  perform app.audit(case when p_open then 'collab.opened' else 'collab.closed' end, 'question_collab', v.id::text);
  return to_jsonb(v);
end$$;

create or replace function public.my_collabs() returns jsonb
language sql stable security definer set search_path = '' as $$
  select coalesce(jsonb_agg(jsonb_build_object(
      'id', c.id, 'title', a.title, 'class', cl.name, 'prompt', c.prompt,
      'mine', (select coalesce(jsonb_agg(jsonb_build_object('id', s.id, 'prompt', s.prompt, 'status', s.status, 'feedback', s.feedback)
                                         order by s.created_at desc), '[]'::jsonb)
               from public.question_submissions s where s.collab_id = c.id and s.student_id = auth.uid()))
      order by c.created_at desc), '[]'::jsonb)
  from public.question_collabs c
  join public.class_members m on m.class_id = c.class_id and m.user_id = auth.uid() and m.role = 'student'
  join public.activities a on a.id = c.activity_id
  join public.classes cl on cl.id = c.class_id
  where c.is_open
$$;

create or replace function public.submit_question(p_collab uuid, p_prompt text, p_options jsonb, p_explanation text)
returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare v_me public.users := app.me(); v_c public.question_collabs; v_n int; v_correct int; v_id uuid;
begin
  select * into v_c from public.question_collabs where id = p_collab;
  if v_c.id is null or not v_c.is_open then raise exception 'Question writing is closed for this quiz.' using errcode = 'P0001'; end if;
  if not exists (select 1 from public.class_members where class_id = v_c.class_id and user_id = v_me.id and role = 'student') then
    raise exception 'This is for another class.' using errcode = '42501';
  end if;
  if jsonb_typeof(p_options) <> 'array' then raise exception 'Add answer choices.' using errcode = '22023'; end if;
  v_n := jsonb_array_length(p_options);
  select count(*) into v_correct from jsonb_array_elements(p_options) o where (o ->> 'correct')::boolean;
  if v_n < 2 or v_n > 6 then raise exception 'Give between 2 and 6 answer choices.' using errcode = '22023'; end if;
  if v_correct <> 1 then raise exception 'Mark exactly one choice as correct.' using errcode = '22023'; end if;
  if exists (select 1 from jsonb_array_elements(p_options) o where length(btrim(coalesce(o ->> 'label', ''))) not between 1 and 300) then
    raise exception 'Every choice needs text (up to 300 characters).' using errcode = '22023';
  end if;
  if length(btrim(coalesce(p_explanation, ''))) < 10 then
    raise exception 'Explain why the correct answer is right (at least one sentence).' using errcode = '22023';
  end if;
  if (select count(*) from public.question_submissions where collab_id = p_collab and student_id = v_me.id and status = 'pending') >= 5 then
    raise exception 'You have 5 questions waiting for your teacher. Wait for feedback before adding more.' using errcode = 'P0001';
  end if;
  insert into public.question_submissions (tenant_id, collab_id, student_id, prompt, options, explanation)
    values (v_me.tenant_id, p_collab, v_me.id, btrim(p_prompt),
            (select jsonb_agg(jsonb_build_object('label', btrim(o ->> 'label'), 'correct', coalesce((o ->> 'correct')::boolean, false)))
             from jsonb_array_elements(p_options) o),
            btrim(p_explanation))
    returning id into v_id;
  return jsonb_build_object('id', v_id);
end$$;

create or replace function public.collab_submissions(p_activity uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  return (select coalesce(jsonb_agg(jsonb_build_object(
      'id', s.id, 'student', u.full_name, 'class', cl.name, 'prompt', s.prompt, 'options', s.options,
      'explanation', s.explanation, 'status', s.status, 'feedback', s.feedback, 'created_at', s.created_at)
      order by (s.status = 'pending') desc, s.created_at), '[]'::jsonb)
    from public.question_submissions s
    join public.question_collabs c on c.id = s.collab_id
    join public.users u on u.id = s.student_id
    join public.classes cl on cl.id = c.class_id
    where c.activity_id = p_activity and app.can_manage_class(c.class_id));
end$$;

create or replace function public.review_question_submission(p_submission uuid, p_action text, p_feedback text default null)
returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare v_me public.users := app.me(); v_s public.question_submissions; v_c public.question_collabs; v_q uuid; v_pos int; v_name text;
begin
  select * into v_s from public.question_submissions where id = p_submission for update;
  if v_s.id is null then raise exception 'Question not found.' using errcode = 'P0002'; end if;
  select * into v_c from public.question_collabs where id = v_s.collab_id;
  if not app.can_manage_class(v_c.class_id) then raise exception 'Not your class.' using errcode = '42501'; end if;
  if v_s.status = 'approved' then raise exception 'Already added to the quiz.' using errcode = 'P0001'; end if;

  if p_action = 'approve' then
    select coalesce(max(position), -1) + 1 into v_pos from public.questions where activity_id = v_c.activity_id;
    select full_name into v_name from public.users where id = v_s.student_id;
    insert into public.questions (tenant_id, activity_id, owner_id, kind, prompt, explanation, points, position, config)
      values (v_s.tenant_id, v_c.activity_id, v_me.id, 'mcq', v_s.prompt, v_s.explanation, 1, v_pos,
              jsonb_build_object('authored_by', app.display_name(v_name)))
      returning id into v_q;
    insert into public.question_options (tenant_id, question_id, label, is_correct, position)
      select v_s.tenant_id, v_q, o.value ->> 'label', (o.value ->> 'correct')::boolean, (o.ordinality - 1)::int
      from jsonb_array_elements(v_s.options) with ordinality o;
    update public.question_submissions set status = 'approved', question_id = v_q, feedback = nullif(btrim(coalesce(p_feedback, '')), ''),
      reviewed_by = v_me.id, reviewed_at = now() where id = p_submission;
    perform app.give_xp(v_s.tenant_id, v_s.student_id, v_c.class_id, 'question', v_s.id, 25, 'Your question was added to the quiz');
    perform app.give_badge(v_s.tenant_id, v_s.student_id, 'author');
  elsif p_action = 'return' then
    if length(btrim(coalesce(p_feedback, ''))) < 3 then
      raise exception 'Tell the student what to improve.' using errcode = '22023';
    end if;
    update public.question_submissions set status = 'returned', feedback = btrim(p_feedback),
      reviewed_by = v_me.id, reviewed_at = now() where id = p_submission;
    perform app.notify(v_s.student_id, 'question_returned', 'Your teacher sent your question back', btrim(p_feedback), '/student', 'info',
                       jsonb_build_object('submission_id', v_s.id));
  else
    raise exception 'Unknown action.' using errcode = '22023';
  end if;
  perform app.audit('collab.' || p_action, 'question_submission', p_submission::text);
  return jsonb_build_object('status', case when p_action = 'approve' then 'approved' else 'returned' end, 'question_id', v_q);
end$$;

-- ---------------------------------------------------------------------------
-- Gradebook: every student and every assignment in a class (CSV export)
-- ---------------------------------------------------------------------------
create or replace function public.class_gradebook(p_class uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not app.can_manage_class(p_class) then raise exception 'Not your class.' using errcode = '42501'; end if;
  return jsonb_build_object(
    'assignments', (select coalesce(jsonb_agg(jsonb_build_object('id', a.id, 'title', a.title, 'due_at', a.due_at,
                      'points', a.points_possible) order by a.due_at nulls last, a.created_at), '[]'::jsonb)
                    from public.assignments a where a.class_id = p_class and a.status <> 'draft'),
    'students', (select coalesce(jsonb_agg(jsonb_build_object('id', u.id, 'name', u.full_name, 'email', u.email,
                   'scores', (select coalesce(jsonb_object_agg(a.id, jsonb_build_object(
                        'score', case when g.score is not null then g.score
                                      when t.max_score > 0 and t.score is not null then round(t.score / t.max_score * a.points_possible, 2) end,
                        'late', s.is_late, 'status', s.status)), '{}'::jsonb)
                      from public.assignments a
                      join lateral (select * from public.submissions s where s.assignment_id = a.id and s.student_id = u.id
                                    order by s.attempt_no desc limit 1) s on true
                      left join public.grades g on g.submission_id = s.id
                      left join public.quiz_attempts t on t.id = s.attempt_id
                      where a.class_id = p_class and a.status <> 'draft'))
                   order by u.full_name), '[]'::jsonb)
                 from public.class_members m join public.users u on u.id = m.user_id
                 where m.class_id = p_class and m.role = 'student'));
end$$;

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------
revoke execute on function public.game_goal(uuid), public.set_student_supports(uuid, uuid, boolean, boolean, int, boolean, text),
  public.class_supports(uuid), public.my_supports(), public.open_question_collab(uuid, uuid, boolean, text), public.my_collabs(),
  public.submit_question(uuid, text, jsonb, text), public.collab_submissions(uuid),
  public.review_question_submission(uuid, text, text), public.class_gradebook(uuid)
  from public, anon;
grant execute on function public.game_goal(uuid), public.set_student_supports(uuid, uuid, boolean, boolean, int, boolean, text),
  public.class_supports(uuid), public.my_supports(), public.open_question_collab(uuid, uuid, boolean, text), public.my_collabs(),
  public.submit_question(uuid, text, jsonb, text), public.collab_submissions(uuid),
  public.review_question_submission(uuid, text, text), public.class_gradebook(uuid)
  to authenticated, service_role;

create or replace function public.health() returns jsonb
language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('ok', true, 'db_time', now(), 'schema', '0800')
$$;

-- Done. Should return 0800:
select public.health() ->> 'schema' as schema;
